### ISSUE TITLE
Ignoring form required validation 

### ISSUE THREAD

**Issue by medaamarnadh** [hayageek/jquery-upload-file#100]
Hi , I am using this plugin for file upload . But i want to give required property to the file .Now the problem is when i submit the form without selecting any file it is submitting . I have observed by debugging it is making the file tag as hidden type . By doing form ignoring required property .
Can you tell me a solution for this .

**Comment by hayageek** [comment]
Can you try with option
nestedForms:false

**Comment by medaamarnadh** [comment]
Hi , Can you tell me where i have to give that option?. Then i will try .

**Comment by hayageek** [comment]
Can you share me ur code ?
How you are initialising the plugin ?

**Comment by hayageek** [comment]
issue is fixed ?
