### ISSUE TITLE
why don't have real file when upload complete 

### ISSUE THREAD

**Issue by kanabut** [hayageek/jquery-upload-file#101]
hi i try to upload file but when progress is complete it not thing happen and don't have the real file in server path "$output_dir = "uploads/";" this one is directory path for keep real file pls help me ?

**Comment by hayageek** [comment]
It should be problem with the folder permission .can you share your URL?

**Comment by kanabut** [comment]
thank you for answer it OK right now, but i have question it possible upload video file ? because when i try it can upload only IMG file but video file can not

**Comment by hayageek** [comment]
There is no difference between image & video file for uploading. Only
thing, you might have some file size limitaion at server side, so video
file is failing.
