### ISSUE TITLE
error when upload file over 500MB

### ISSUE THREAD

**Issue by kanabut** [hayageek/jquery-upload-file#105]
hi i try to upload file OVER 500MB but sometime it possible to upload and sometime it show error pls help me 

thank you

**Comment by claide** [comment]
Check console if what error you got to be more specific.

**Comment by hayageek** [comment]
check your PHP configuration, below fields. What is your maximum values ?

max_file_uploads = 2000
upload_max_filesize = 40000M
max_input_vars = 10000
post_max_size = 40000M
