### ISSUE TITLE
jquery-upload-file and insert data to mysql

### ISSUE THREAD

**Issue by nameman** [hayageek/jquery-upload-file#107]
HI all
I have a problem with this plugin. I try to change the upload.php file so that after you load a .txt file type should I update MySQL-table indicating the file name, size, and upload date, but I always get only the following error: "ERROR: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data "and firegub does not provide any information.
How can I check for errors ajax?

Someone has already implemented the upload.php file with the update of a database?

Thanks for your help.

P.S. sorry for my English ... :)

**Comment by hayageek** [comment]
JSON.parse error comes if you return non-JSON data in upload.php.

**Comment by nameman** [comment]
....oh! ..... THANKS! 
sorry ... my knowledge of ajax is very low ....
