### ISSUE TITLE
Error when jQuery Validation submitted

### ISSUE THREAD

**Issue by hawm3d** [hayageek/jquery-upload-file#109]
I use both jquery-upload-file and jquery-validation on a page. When I submit my form, show me this message: 
**Uncaught TypeError: Cannot read property 'settings' of undefined**
I remove: 
`if($.fn.ajaxForm == undefined) {
        $.getScript(("https:" == document.location.protocol ? "https://" : "http://") + "malsup.github.io/jquery.form.js");
    }`
from jquery-upload-file and jquery-validation works fine but jquery-upload-file doesn't work.
What should I do?

**Comment by hayageek** [comment]
Can you share me your code?

**Comment by hawm3d** [comment]
[JSFiddle](https://jsfiddle.net/jc8mLbgx/2/)
Submit form and look at console.

**Comment by hayageek** [comment]
Hi, Use the option
nestedForms:false

https://jsfiddle.net/jc8mLbgx/6/
