### ISSUE TITLE
Load items in "loaded" order

### ISSUE THREAD

**Issue by nacesprin** [hayageek/jquery-upload-file#111]
Hello. Why the items are shown in opposite order which are loaded?
I explain. When the array data below is loaded:
```
[0:{name: "first", path: "1", size: 1},
1:{name: "second", path: "2", size: 2},
2:{name: "third", path: "3", size: 3},]
```

the items are appended like:
```
<div>third</div>
<div>second</div>
<div>first</div>
```

and i must to set showFileCounter = false due to is assiged:

`1) to element <div>third</div>, 2) to element <div>second</div> and 3) to <div>first</div>`

There is no way to implement any option in order to set the loaded elements order like asc/desc?

**Comment by hayageek** [comment]
there is already an option for that.

uploadQueueOrder:'top'
uploadQueueOrder:'bottom'

**Comment by nacesprin** [comment]
It is not in the documentation. Please, document uploadQueueOrder and add the "pd" parameter on downloadCallback. Thanks for that!
