### ISSUE TITLE
Access to ProgressDiv on downloadCallback

### ISSUE THREAD

**Issue by nacesprin** [hayageek/jquery-upload-file#117]
Finally, forked and commited modifications to access progressDiv from downloadCallbacks

https://github.com/hayageek/jquery-upload-file/pull/116

**Comment by hayageek** [comment]
Hi
Can you make progressDiv as the third argument for downloadCallback(),
If anybody using downloadCallback, it will affect them,.

Can you rebase and make only one commit

**Comment by hayageek** [comment]
Merged your changed. Thanks for your contribution.
