### ISSUE TITLE
Cannot upload the same file without refreshing browser

### ISSUE THREAD

**Issue by RiderMayBail** [hayageek/jquery-upload-file#119]
Your plugin is working great, but I am running into an issue with one aspect of the implementation. 

I use this to upload a single Excel workbook to my site, where it is saved to the server, read via PHP and certain values are sent back to the page, and the file is deleted from the server (am not storing the file).

All of this works perfectly, but only 1 time. If for some reason I need to upload the file again, it does not upload at all, unless I refresh the browser.

I have not set the sequential option, so it should not be limited to 1. I do not see any other options in the documentation that would indicate preventing/allowing the upload of a file again.

Edit: Sorry, forgot to mention I'm using 4.0.10
Thank you

**Comment by hayageek** [comment]
Surely there should not be problem with the plugin.
Can you share your URL?
You can send mail to hayageek@gmail.com

**Comment by RiderMayBail** [comment]
[importIWall.php.txt](https://github.com/hayageek/jquery-upload-file/files/385212/importIWall.php.txt)
[importIW.js.txt](https://github.com/hayageek/jquery-upload-file/files/385213/importIW.js.txt)

Thank you for the response, unfortunately the site is located behind a corporate firewall and not accessible outside. I have attached files with the sections of code related to this problem. I've commented out a majority of the code to limit the amount of work that is being done, to hopefully isolate the issue, but it is still present.

The way I've commented it out, The javascript and file upload is triggered by the click of a button, we're then posting that to the PHP page, and on the PHP page, we're not doing anything with it other than moving the file to a specific folder and echoing the filepath and name back to the AJAX success function (through line 28). The AJAX is mostly commented out, so that we are basically just sending the returned path to the console (line 38).

What happens is the first upload of the file, everything works great. If I try to upload the file again, absolutely nothing happens. If I refresh the page it works the first time again, then nothing.

The script I'm including in my HTML file is http://hayageek.github.io/jQuery-Upload-File/4.0.10/jquery.uploadfile.min.js

I hope this is enough information, if something is missing that would be beneficial, I would be happy to try and supply it. I've even tried this on different web servers with the same result.

Thank you

**Comment by RiderMayBail** [comment]
I found the problem, while it was with the upload, it was not with your plugin. 

It turned out to be that my upload routine was triggered by the change of the file input field, but the value was retained in the field after file upload. Clearing that field, as part of the routine fixes this issue.

Excellent plugin.
