### ISSUE TITLE
How add dynamicFormData for each file upload?

### ISSUE THREAD

**Issue by hervispichardo** [hayageek/jquery-upload-file#121]
Awesome plugin, congratulations.

I'm trying to send a text field for the title with each image.
Is this possible? upload multiple images and send an extra field for each?

[This is my code fiddle](https://jsfiddle.net/hervis15/czvqm5dt/3/)

And my php file
`<?php
$output_dir = "media/";
if(isset($_FILES["myfile"]))
{
	$ret = array();
	
//	This is for custom errors;	
/*	$custom_error= array();
	$custom_error['jquery-upload-file-error']="File already exists";
	echo json_encode($custom_error);
	die();
*/
	$error =$_FILES["myfile"]["error"];
	//You need to handle  both cases
	//If Any browser does not support serializing of multiple files using FormData() 
	if(!is_array($_FILES["myfile"]["name"])) //single file
	{
 	 	$fileName = $_FILES["myfile"]["name"];
 		move_uploaded_file($_FILES["myfile"]["tmp_name"],$output_dir.$fileName);
    	$ret[]= $fileName;
	}
	else  //Multiple files, file[]
	{
	  $fileCount = count($_FILES["myfile"]["name"]);
	  for($i=0; $i < $fileCount; $i++)
	  {
	  	$fileName = $_FILES["myfile"]["name"][$i];
		move_uploaded_file($_FILES["myfile"]["tmp_name"][$i],$output_dir.$fileName);
	  	$ret[]= $fileName;
	  }
	
	}
    echo json_encode($ret);
 }
 $title = $_POST["title"];
 echo $title;
 ?>`

Thank you

**Comment by hayageek** [comment]
You code looks perfect.
It is not working in jsfiddle, because of cross-domain.
What is the error you are getting ?

**Comment by hayageek** [comment]
issue is solved ?

**Comment by hervispichardo** [comment]
Yes, thank you...
