### ISSUE TITLE
Not working - no errors

### ISSUE THREAD

**Issue by petrakid** [hayageek/jquery-upload-file#122]
I set both the client side and server side up as instructed.  When I try to upload an image, the progress bar shows and completes, and the image preview is there too.  But the image does not get uploaded.  There aren't any errors either in the error_log file on the server or in my browsers console.  The folder permissions are set to 755.

Here's client side:
`<div id="fileuploader">Upload</div>

$(document).ready(function()
{
    $("#fileuploader").uploadFile({
          url:"<?php echo $_SESSION['sitevars']['siteurl'] ?>/js/ajax_query.php",
          multiple:true,
          dragDrop:true,
          formData: {"c_id":"<?php echo $data['c_id'] ?>","last_name":"<?php echo $data['last_name'] ?>"},
          fileName:"client_files",
          acceptFiles:"image/*",
          showPreview:true,
          previewHeight: "100px",
          previewWidth: "100px"  
    });
});`

As you can see I create some POST variables using PHP

Here's server side:
`if(isset($_FILES['client_files'])) {
     $ret = array();
     $error = $_FILES["client_files"]["error"];

```
 $output_dir = $_SESSION['sitevars']['siteroot'] .'/clients/'. $_POST['last_name'] . $_POST['c_id'] .'/docs/';

    if(!is_array($_FILES["client_files"]["name"])) { // single files
      $ext = pathinfo($_FILES['client_files']['name'], PATHINFO_EXTENSION);
      $filename = rand(6,8) .'.'. $ext;
    move_uploaded_file($_FILES["client_files"]["tmp_name"], $output_dir . $filename);
    $ret[]= $filename;
} else {  //Multiple files, file[]
      $filecount = count($_FILES["client_files"]["name"]);
      for($i=0;$i<$filecount;$i++) {
           $ext = pathinfo($_FILES['client_files']['name'][$i], PATHINFO_EXTENSION);
           $filename = rand(6,8) .'.'. $ext;
           move_uploaded_file($_FILES["client_files"]["tmp_name"][$i],$output_dir . $filename);
           $ret[] = $filename;
      }
 }
 echo json_encode($ret);
```

}`

I want the stored filename to be a random set of numbers using rand() followed by the extension of the file itself.  I checked the SESSION variables to make sure they're in the $output_dir and they are.
Jquery is loaded, version 1.2.something, as well as the uploadfile.min.js file (both loaded in the HEAD of the page) and the css files.

What am I missing??

**Comment by hayageek** [comment]
In the upload.php firs line add the code
var_dump($_FILES);
Then see the response in browser.  Whether files are sent or not

You did not share client code

**Comment by petrakid** [comment]
I did share client side, but it didn't share as a code block even though I put it in a code block.  At any rate:

I did a var_dump and nothing printed.

Here's the client code once again.  Hopefully it'll print right:

`$(document).ready(function()
{
	$("#fileuploader").uploadFile({
          url:"http://pantry.stpaullutheranbham.org/js/ajax_query.php",
          multiple:true,
          dragDrop:true,
          formData: {"c_id":clientid},  // global variable
          fileName:"client_files",
          acceptFiles:"image/*",
          showPreview:true,
          previewHeight: "100px",
          previewWidth: "100px"          
	});
});`

**Comment by petrakid** [comment]
Also there are no PHP errors in either the log file or displayed on screen.

**Comment by petrakid** [comment]
And here's the code for the php file (this is an include file, called into a much larger ui.):

```
<?php
$sql = $db->query("SELECT c_id, last_name, first_name FROM pan_clients WHERE client_status != 9 ORDER BY last_name ASC");
?>
<link href="http://hayageek.github.io/jQuery-Upload-File/4.0.10/uploadfile.css" rel="stylesheet" />
<script src="http://hayageek.github.io/jQuery-Upload-File/4.0.10/jquery.uploadfile.min.js"></script>

<script type="text/javascript">
var clientid;
function selectClient(svalue)
{
     clientid = svalue;
     $.ajax({
          url: 'http://<?php echo $_SESSION['sitevars']['siteurl'] ?>/js/ajax_query.php',
          type: 'POST',
          data: {
               'get_docs':true,
               'client_id':svalue
          },
          success: function(data) {
               document.getElementById("hidden_panel").style.display = "block";
               document.getElementById("results").innerHTML = data;
          }
     });     
}
</script>
<div class="col-lg-12">
<div class="panel panel-default">
<div class="panel-heading">Select a Client to view documents.</div>
<div class="panel-body">
<div class="col-lg-4">
<label>Select a Client:</label>
<select name="c_id" id="c_id" class="form-control" onchange="selectClient(this.value)">
<option value="">Select</option>
<?php
while($row = $sql->fetch(PDO::FETCH_ASSOC)) {
     echo '<option value="'. $row['c_id'] .'">'. $row['last_name'] .', '. $row['first_name'] .'</option>';
}
?>
</select>
</div>
<div class="col-lg-8"></div><br />
<hr /><br />
<div id="hidden_panel" class="col-lg-12" style="display: none;">
<div class="panel panel-default">
<div class="panel-heading">Saved Documents</div>
<div class="panel-body" id="results">


</div>
</div>
<div class="row">

<div id="fileuploader">Upload</div>
</div>
</div>
</div>
<script>
$(document).ready(function()
{
	$("#fileuploader").uploadFile({
          url:"<?php echo $_SESSION['sitevars']['siteurl'] ?>/js/ajax_query.php",
          multiple:true,
          dragDrop:true,
          formData: {"c_id":clientid},
          fileName:"client_files",
          acceptFiles:"image/*",
          showPreview:true,
          previewHeight: "100px",
          previewWidth: "100px"          
	});
});
</script>
</div>
</div>
```

**Comment by hayageek** [comment]
what is the response for the request ? you can check in the browser.

**Comment by sgutauckis** [comment]
I am experiencing the same exact issue just trying to use the demo.html
Everything looks like it worked but nothing gets uploaded.

**Comment by hayageek** [comment]
solved ?

**Comment by sgutauckis** [comment]
no not solved...

**Comment by hayageek** [comment]
can you check whether the uploads folder has the  access, to write files.

**Comment by apzeiro** [comment]
the files are sent for which folder?
Do I need to create one folder? Where?

**Comment by hayageek** [comment]
in upload.php, you can configure the directory. You need to create the directory

**Comment by hayageek** [comment]
solved ?

**Comment by apzeiro** [comment]
No, I gave up using it. Thanks.
