### ISSUE TITLE
Uncaught TypeError: obj.createProgress is not a function

### ISSUE THREAD

**Issue by leeson-w** [hayageek/jquery-upload-file#125]
when using " onLoad", i got this error, please help, thank you!
VM1860:133 Uncaught TypeError: obj.createProgress is not a function
onLoad @ VM1860:133
F @ jquery.uploadfile.min.js:8
e.fn.uploadFile @ jquery.uploadfile.min.js:8
handler @ VM1860:116

## the code is here:
var updateObj = $("#fileuploader").uploadFile({
 url:"/admin/cities/"  + row.id,
 method: "PUT",
 fileName:"img",
 dynamicFormData: function() {
 	 var data = { name: 'test', subtitle: 'test title', order: 5 };
 	 return  data; 
 }, 
 showPreview: true,
 previewHeight: "100px",
 previewWidth: "100px",
 onLoad: function(obj) {
 	obj.createProgress(row.img);
 },
 onSelect:function(files) {
 	fileSelected = true;
 },	
 autoSubmit: false,
 onSuccess:function(files,data,xhr,pd) {
 	 if (data.retCode == 0) {
     form.form('reset');
     dialog.dialog('close');
     dataTable.datagrid('reload');   
     updateObj.reset();                   	                     
   } else {
     $.messager.alert('prompt', 'Add Failed');
   }
 },
 onError: function(files,status,errMsg,pd) {
 	$.messager.alert('prompt', 'Upload Failed');
 }
);

**Comment by hayageek** [comment]
I need to update the documentation. createProgress syntax is wrong.
correct is:
function.createProgress (filename,filepath,filesize)

**Comment by leeson-w** [comment]
could you give me an example? can not get your point, thanks

**Comment by hayageek** [comment]
check the section "12).Show already uploaded files"  in features tab

**Comment by leeson-w** [comment]
great, it's working now, i met another issue and making a new one
