### ISSUE TITLE
"update" not working

### ISSUE THREAD

**Issue by leeson-w** [hayageek/jquery-upload-file#127]
i'm using "update" to update the url on runtime, but it seems not working, the initial url is still being used. 

here is the code:
`var iconObj = $("#caticon").uploadFile({
  url:"/admin/categories/",
  fileName:"icon",
  method: "PUT",
  autoSubmit: false,
  onSuccess:function(files,data,xhr,pd) {  
     if (data.retCode == 0) {  
       $.messager.alert('Prompt', 'Update Success');  
    } else {
      $.messager.alert('Prompt', 'Update Failed');
    }
  },  
  onError: function(files,status,errMsg,pd) {
    $.messager.alert('Prompt', 'Upload Failed');
  }
});                      

$.ajax({
    method: "GET",
    cache: false,
    url: "/admin/cities/" + row.id,
    dataType: "json",
    success: function(data) {
        if (data.retCode == 0) {
          var url = "/admin/categories/" + data.category.id;
          iconObj.update({url:url});
          iconObj.startUpload();
        } else {
      $.messager.alert('Prompt', 'Query Category Failed');
    }
    }
});`

i add "console.log" to print out the new url, actually the url is updated when update executing, but when startUpload runs, initial url is used instead.

**Comment by hayageek** [comment]
Yes it is an issue.  I will fix it.

**Comment by hayageek** [comment]
Fixed.
