### ISSUE TITLE
Can my upload begin from the top of the list instead of bottom of the list when I select multiple files

### ISSUE THREAD

**Issue by ViperLiu** [hayageek/jquery-upload-file#133]
When I was trying to upload multiple file at once,it always begin upload from the bottom of the file list
like this:

upload button and drag & drop field 
5.jpg                                                <- the part which users can see
4.jpg                                                <- the part which users can see
3.jpg
2.jpg
1.jpg                                                <- upload starts from here,and users can't see it without scrolling down

when it comes to a large number of files, e.g. more than 50, the upload progress bar will be showed in the bottom of the page,which users might be confused that nothing is uploading(actually the upload begin from the bottom where users can't see it without scrolling down)

what I want is like this:

upload button and drag & drop field
1.jpg                                               <- upload starts from here,where users can see it without scrolling down
2.jpg
3.jpg
4.jpg
5.jpg

**Comment by hayageek** [comment]
use the option uploadQueueOrder:'bottom'

by default it is 'top'

**Comment by ViperLiu** [comment]
OK,thanks
And maybe you should add this to your documentation
