### ISSUE TITLE
Multi uploads on a page

### ISSUE THREAD

**Issue by zaid26** [hayageek/jquery-upload-file#134]
If initialized by class , only one widget works, how to activate multiple .

**Comment by sonha** [comment]
I have same question with zaid26 :D

**Comment by hayageek** [comment]
if your class name is 'test'

$('.test).each(function()
{
  $(this).uploadFile(options);
});

**Comment by zaid26** [comment]
Thanks @hayageek  !

**Comment by aditya1122** [comment]
how to get the response that all uploads are completed if some objects have file to be uploaded and some does not. Also autosubmit is false.
