### ISSUE TITLE
 extraObj.startUpload(); Doble File

### ISSUE THREAD

**Issue by awilchesl** [hayageek/jquery-upload-file#135]
Hello, I need to send a file using startUpload(); But when validating the console sends it twice. I would like to know if it is a mistake and how to solve it

`var extraObj = $("#fileuploader").uploadFile({Options});
dynamicFormData: function()
    {
    var data ={ generals:$(".test").val()}
    console.log(data);
    return data;
    },
$("#extrabutton").click(function()
{
  extraObj.startUpload();
});`

`Console.log(data)` Prints the request twice

**Comment by hayageek** [comment]
It does not send the file twice.
If you select two files, it will send two requests. one request per file.

If you want all the files in single request serialize:false
