### ISSUE TITLE
How can I add a Callback about verify state?

### ISSUE THREAD

**Issue by chang0022** [hayageek/jquery-upload-file#136]
When verifying is failed, i want to popup the error message. But I can't get the it. Now I  only can changed this style.
: ） Forgive my English bad.

**Comment by hayageek** [comment]
Do you want to get custom error from Server ?

check "Custom Errors"  in http://hayageek.com/docs/jquery-upload-file.php#doc
one more thing, you have to set returnType:"json"

**Comment by chang0022** [comment]
Sorry, you may have misunderstood，I mean, the error like this "is not allowed. Maximum allowed files are: " "is not allowed. Allowed Max size: ". These error are before sent to Server, I want to use a pupup to show them.

**Comment by hayageek** [comment]
No option. You need to modify the plugin.
Add your popup code, wherever you find `obj.errorLog`

**Comment by chang0022** [comment]
OK. Thx
