### ISSUE TITLE
Not saved

### ISSUE THREAD

**Issue by josvenes** [hayageek/jquery-upload-file#145]
Made subdir under demo => uploads"
upload.php => $output_dir = "uploads/"; 
Webpage works: files are uploaded

But not saved!
No errormessge.

What could be wrong?

**Comment by hayageek** [comment]
Issue might be with folder permissions.
Can you share me your URL ?

**Comment by josvenes** [comment]
Hello, and thanks for the reaction:

http://venes.biz/vergadering/_testmap/uploaderhayageek/demo/demo.html

The uplaodmap=
http://venes.biz/vergadering/_testmap/uploaderhayageek/demo/uploads

folder permission=777

greetings Jos


Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: Ravishanker Kusuma<mailto:notifications@github.com>
Verzonden: maandag 24 april 2017 16:06
Aan: hayageek/jquery-upload-file<mailto:jquery-upload-file@noreply.github.com>
CC: josvenes<mailto:venes@live.nl>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [hayageek/jquery-upload-file] Not saved (#145)


Issue might be with folder permissions.
Can you share me your URL ?

**Comment by hayageek** [comment]
Did you see upload.php response. This is the error.
<br />
<b>Fatal error</b>:  Call to undefined function file_put_content() in <b>/home/p22562/domains/venes.biz/public_html/vergadering/_testmap/uploaderhayageek/php/upload.php</b> on line <b>14</b><br />

actually it is file_put_contents() not file_put_content().

**Comment by josvenes** [comment]
Ravishankar


I removed the line. I added it for test.

Checking in firefox/network therer seems to be no troubles but the files arent moved.

Strange


//Jos



Verzonden vanuit Outlook<http://aka.ms/weboutlook>


________________________________
Van: Ravishanker Kusuma <notifications@github.com>
Verzonden: dinsdag 25 april 2017 05:18
Aan: hayageek/jquery-upload-file
CC: josvenes; Author
Onderwerp: Re: [hayageek/jquery-upload-file] Not saved (#145)


Did you see upload.php response. This is the error.


Fatal error: Call to undefined function file_put_content() in /home/p22562/domains/venes.biz/public_html/vergadering/_testmap/uploaderhayageek/php/upload.php on line 14

actually it is file_put_contents() not file_put_content().

**Comment by hayageek** [comment]
can you send your upload.php code ?

**Comment by hayageek** [comment]
<br />
<b>Warning</b>:  move_uploaded_file(uploads/Screen Shot 2017-04-18 at 1.51.56 PM.png) [<a href='function.move-uploaded-file'>function.move-uploaded-file</a>]: failed to open stream: No such file or directory in <b>/home/p22562/domains/venes.biz/public_html/vergadering/_testmap/uploaderhayageek/php/upload.php</b> on line <b>20</b><br />
<br />
<b>Warning</b>:  move_uploaded_file() [<a href='function.move-uploaded-file'>function.move-uploaded-file</a>]: Unable to move '/tmp/php0Y8lr3' to 'uploads/Screen Shot 2017-04-18 at 1.51.56 PM.png' in <b>/home/p22562/domains/venes.biz/public_html/vergadering/_testmap/uploaderhayageek/php/upload.php</b> on line <b>20</b><br />
["Screen Shot 2017-04-18 at 1.51.56 PM.png"]

**Comment by hayageek** [comment]
This might help you

**Comment by josvenes** [comment]
upload.php code



<?php
$output_dir = "uploads/";
if(isset($_FILES["myfile"]))
{
$ret = array();
// This is for custom errors;
/* $custom_error= array();
$custom_error['jquery-upload-file-error']="File already exists";
echo json_encode($custom_error);
die();
*/
$error =$_FILES["myfile"]["error"];

//You need to handle  both cases
//If Any browser does not support serializing of multiple files using FormData()
if(!is_array($_FILES["myfile"]["name"])) //single file
{
  $fileName = $_FILES["myfile"]["name"];
  move_uploaded_file($_FILES["myfile"]["tmp_name"],$output_dir.$fileName);

    $ret[]= $fileName;
}
else  //Multiple files, file[]
{
 $fileCount = count($_FILES["myfile"]["name"]);
 for($i=0; $i < $fileCount; $i++)
 {
  $fileName = $_FILES["myfile"]["name"][$i];
move_uploaded_file($_FILES["myfile"]["tmp_name"][$i],$output_dir.$fileName);
  $ret[]= $fileName;

 }
}
    echo json_encode($ret);
 }
 ?>



Verzonden vanuit Outlook<http://aka.ms/weboutlook>


________________________________
Van: Ravishanker Kusuma <notifications@github.com>
Verzonden: dinsdag 25 april 2017 08:57
Aan: hayageek/jquery-upload-file
CC: josvenes; Author
Onderwerp: Re: [hayageek/jquery-upload-file] Not saved (#145)


can you send your upload.php code ?

**Comment by josvenes** [comment]
Ravishanker


I've solved it!


Got warning in firefox: HTTP wrapper does not support writeable connections

So i changed http:// in //home (server path)

And it worked!


Thanks for your kind help!


//Jos Venes


Verzonden vanuit Outlook<http://aka.ms/weboutlook>


________________________________
Van: Ravishanker Kusuma <notifications@github.com>
Verzonden: dinsdag 25 april 2017 08:57
Aan: hayageek/jquery-upload-file
CC: josvenes; Author
Onderwerp: Re: [hayageek/jquery-upload-file] Not saved (#145)


can you send your upload.php code ?
