### ISSUE TITLE
I want to know how to custom this plugin views?

### ISSUE THREAD

**Issue by wasd11203** [hayageek/jquery-upload-file#146]
dear :
I try to custom own document styles.But i don't know how to do it.
And i'm not find way that  custom  this plugin progress  bar .
please teach me how to do it.

Thanks!

**Comment by hayageek** [comment]
Check the demos page.
http://hayageek.com/docs/jquery-upload-file.php

In features tab,  section 8).Custom UI

**Comment by wasd11203** [comment]
thank you for your answer。
