### ISSUE TITLE
ERROR: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by pigobyte** [hayageek/jquery-upload-file#15]
Hello everyone,
I'm trying the demo but finished the file transfer I getting this error .. ERROR: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
can someone help me?

thank you very much ..

Luca

**Comment by ahmedaeg** [comment]
i have the same error could you help me here is my json http://shops974.com/test.php
here is my code

<?php 

include ("config.php");	

mysql_query("SET NAMES 'utf8'"); 
mysql_query('SET CHARACTER SET utf8');

$query = "SELECT cat_name,cat_img FROM categorytable WHERE  cat_id >= 1";
$result = mysql_query($query);

$rows = array();

while ($r=mysql_fetch_assoc($result)){		    
//	$cat = $r['cat_name'];
//	$catimg = $r['cat_img'];
//	echo $cat ;
//	echo "<br/>";
//	echo $catimg;	
	$rows[] =$r; 
} 

$encoded = json_encode($rows);



echo $encoded;


?>

**Comment by hayageek** [comment]
Hi
Your server code is returning non-json text. Can you check that

**Comment by ahmedaeg** [comment]
the problem on server?? so should i contact the support of server or contact who??

**Comment by hayageek** [comment]
Share me the url
I will tell u the problem

**Comment by ahmedaeg** [comment]
http://tropaeolum.arvixe.com/Default.aspx?pid=SpaceFileManager&SpaceID=4862
url of json or server

**Comment by ahmedaeg** [comment]
is that url you wanted?

**Comment by ahmedaeg** [comment]
any help?

**Comment by KaderUzun** [comment]
Everthing is ok in my local server. But when i upload to internet, while listing uploaded file, "ErrorSyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data" error message shown.  There is no directory permission problem.

**Comment by hayageek** [comment]
Can you check what response coming from server. Open Mozilla -> right
click->inspect element -> network tab

**Comment by KaderUzun** [comment]
Thank you for quick reply.
My server response 

<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>..../UploadHandler.php</b> on line <b>299</b><br />
<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>..../UploadHandler.php</b> on line <b>780</b><br />
<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>..../UploadHandler.php</b> on line <b>804</b><br />
<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>..../UploadHandler.php</b> on line <b>806</b><br />
<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>..../UploadHandler.php</b> on line <b>809</b><br />
<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>..../UploadHandler.php</b> on line <b>812</b><br />
<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>..../UploadHandler.php</b> on line <b>815</b><br />
<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>..../UploadHandler.php</b> on line <b>819</b><br />
<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>..../UploadHandler.php</b> on line <b>822</b><br />
<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>..../UploadHandler.php</b> on line <b>826</b><br />
<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>..../UploadHandler.php</b> on line <b>832</b><br />
<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>..../UploadHandler.php</b> on line <b>885</b><br />
<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>..../UploadHandler.php</b> on line <b>905</b><br />
<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>..../UploadHandler.php</b> on line <b>963</b><br />
<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>..../UploadHandler.php</b> on line <b>971</b><br />
<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>..../UploadHandler.php</b> on line <b>1048</b><br />
{"files":[{"name":"68647- (5).jpg","size":77221,"type":"image\/jpeg","url":"...\/68647-%20%285%29.jpg","thumbnailUrl":"...\/thumbnail\/68647-%20%285%29.jpg","deleteUrl":"...\/index.php?file=68647-%20%285%29.jpg","deleteType":"DELETE"}]}



i think the reason of these warnings  \ mark  in these lines  $file = new \stdClass();

how can i stop these warnings?

**Comment by KaderUzun** [comment]
i removed \ character from related lines in UploadHandler.php file. And now everything is ok. Thank you for your help...

**Comment by AndyNormore** [comment]
I can confirm!

I was able to resolve this plugin issue. I installed another plugin which modified my post and comments via a filter. It was adding extra junk. So, in effect it would destroy the json stream!!! It was returning post data + json stream.

I found this by looking at the "NETWORK" tab in firefox, and seeing the data. From there it was obvious that I had to modify that plugin. 

Everything works great now :dancer:

**Comment by adeiming** [comment]
how to rename file uploaded to custom file name? and how to sort file name with new file uploaded?

**Comment by delongi** [comment]
Hi  hayageek,
i have same error 
As u said i have problem in my Response
my response returns this:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
 <head>
  <title>Index of /upload</title>
 </head>
 <body>
<h1>Index of /upload</h1>
<ul><li><a href="/"> Parent Directory</a></li>
<li><a href="banner/"> banner/</a></li>

</ul>
</body></html>

it lists the folder contains.


i tested your simple code for json testing and it works. 
I created the file test.php and it returns {"name": "Ravi"}

i disabled folder listing in apache config but i received permission error.
i use wamp server on windows , 

Apache Version :
    2.4.4  
PHP Version :
    5.4.16

**Comment by hayageek** [comment]
upload path is not set properly. are u able to access the upload URL from
browser?

**Comment by delongi** [comment]
yes i have access to the URL directly.
upload URL returns the same response and lists the folder .

both of those return same:
request: {
			endpoint: 'http://localhost/upload/'
		},
or 
request: {
			endpoint: '/'
		},
in my view i just need to set an simple URL in endpoint witch mention to a vacant folder .
Is there any specific configs for this folder?

**Comment by musichaws** [comment]
Hi @hayageek I see you helping many people on this matter, can you help me too?

I am also getting this error message: 
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

My site was working absolutely fine and today (30th Oct) one customer told me that during checkout, the "place order" was greyed-out, and cannot proceed with it.
My last order was 26th Oct. I tried to restore to 26th or even 24th, the problem still exist. 
The only different i have made is on 24th i installed W3Total Cache, but anyhow, the order still went through until 26th, even i restore to 22nd, the problem still exist (which shouldn't be existed that time)

I'm using wordpress 4.3.1, woocommece 2.4.6

This is my url http://akiddo.com.my

Million thanks...

**Comment by hayageek** [comment]
Upload.php returns non-JSON  data. Check the response. Looks like some
warnings in the upload.php. Plugins is unable parse the JSON response

**Comment by musichaws** [comment]
Thanks for the prompt reply @hayageek 
What you suggest me to do? What file to look for? Cause i'm a half IT guy, not very very familiar with all this.

**Comment by hayageek** [comment]
Don't look in the code , in the browser see the response
In Firefox, right click "Inspect Elemnet" , then "Network", see the
response of upload.php

**Comment by musichaws** [comment]
Hi what i found is the syntax error at this file http://akiddo.com.my/checkout/?wc-ajax=checkout

but... what exactly should i do? @hayageek

**Comment by hayageek** [comment]
You need to fix the syntax error. I can not access the web page. Can you
send me the URL ?.

**Comment by musichaws** [comment]
You mean my site url? http://akiddo.com.my
Please lemme know if you need more info...

**Comment by musichaws** [comment]
basically all the ajax related matters doesn't work.
For example, when hover over shopping cart, products should show, and when "add to cart" the shopping cart should show up automatically.
The ajax search doesn't work also...

**Comment by musichaws** [comment]
THank god, i think the restore worked! Now everthing is okay. The restore might not take effect immidately because of the cached is it?

**Comment by garrablanka** [comment]
Hi @hayageek ...
the code works very good but if i change returnType: null to returnType: "json", i have problems because the file is not uploaded and it returns

SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

Can you help me please??
here is the link --> http://www.lompros.com/multipleupload.php?quien=garrablankactm&num=69

PS. I created the file example to try json and it returns from server {"name": "Ravi"}

**Comment by shriyais** [comment]
Upload doesn't work in Windows but it's working fine in Android & iOS. In detail, on the click of the upload button the file browser doesn't open.
We have used the upload plugin from hayageek.com: jquery.uploadfile.min.js & uploadfile.css
Please suggest a solution urgently - any help is appreciated.

**Comment by hayageek** [comment]
Json error because , you are returning NON-JSON data.
Not working in Windows may be because is script errors ,  check any extra
comma for the element in uploader settings .

Which browser you are using windows ?

**Comment by garrablanka** [comment]
thanks @hayageek 
and how can i fix the json error? NON-JSON data??

**Comment by hayageek** [comment]
check the upload.php response, in browser. you added some 'echo' statements
or some PHP warnings.

**Comment by shriyais** [comment]
Thanks Ravishanker!
We'll cross-check with our mobile dev team & let you know.

Check back with us - we'll keep your updates.

-MyLegalNet

On Sat, Dec 12, 2015 at 4:07 PM, Ravishanker Kusuma <
notifications@github.com> wrote:

> Json error because , you are returning NON-JSON data.
> Not working in Windows may be because is script errors , check any extra
> comma for the element in uploader settings .
>
> Which browser you are using windows ?
>
> On Saturday, 12 December 2015, Shriya Innovative Solutions <
> notifications@github.com> wrote:
>
> > Upload doesn't work in Windows but it's working fine in Android & iOS. In
> > detail, on the click of the upload button the file browser doesn't open.
> > We have used the upload plugin from hayageek.com:
> > jquery.uploadfile.min.js & uploadfile.css
> > Please suggest a solution urgently - any help is appreciated.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/hayageek/jquery-upload-file/issues/15#issuecomment-164135938
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hayageek/jquery-upload-file/issues/15#issuecomment-164138242>
> .
>



-- 
*Shriya Innovative Solutions*
http://www.shriyais.com

**Comment by garrablanka** [comment]
very thanks @hayageek !!

**Comment by shriyais** [comment]
Hayageek,

We're using PhoneGap and the web-service is coded in asmx
The problem we're having is on-click of the UPLOAD button, the file-uploader doesn't open up or display.

For your information, we're using jquery.uploadfile.min.js & uploadfile.css

We appreciate your assistance and we're looking forward to your reply!

**Comment by hayageek** [comment]
can you set the option

nestedForms : false

**Comment by shriyais** [comment]
Hayageek,

Can you please elaborate where to make the above changes? If in the js file, then where?

**Comment by VipSaran** [comment]
@shriyais just follow the [basic examples](http://hayageek.com/docs/jquery-upload-file.php#preview) and initialize the plugin with `nestedForms: false`:

```
$("#singleupload").uploadFile({
url:"upload.php",
multiple:false,
dragDrop:false,
maxFileCount:1,
nestedForms: false,
fileName:"myfile"
}); 
```

**Comment by hayageek** [comment]
Do you still have json.parse error ?

**Comment by shriyais** [comment]
Hayageek,
We're not getting any errors. The problem we're having is that in Windows, when we click the "file upload" button - no event triggers. The file browser window doesn't launch like it does in iOS & Android.
So once again, in Windows when we click the "file upload" button - nothing happens. It's doesn't launch the file browser window so this prevents us from selecting files.

Thanks for your help!

**Comment by josvenes** [comment]
I read al; he answerd/ dit the check with chromef12/network and got the following anwers (i replaced my adress with test.biz)

Warning: move_uploaded_file(/home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/files/compressed.tracemonkey-pldi-09 (2).pdf) [function.move-uploaded-file]: failed to open stream: Permission denied in /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php on line 1079

Warning: move_uploaded_file() [function.move-uploaded-file]: Unable to move '/tmp/phpqrKFPA' to '/home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/files/compressed.tracemonkey-pldi-09 (2).pdf' in /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php on line 1079

Warning: filesize() [function.filesize]: stat failed for /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/files/compressed.tracemonkey-pldi-09 (2).pdf in /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php on line 294

Warning: unlink(/home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/files/compressed.tracemonkey-pldi-09 (2).pdf) [function.unlink]: No such file or directory in /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php on line 1098

Warning: Cannot modify header information - headers already sent by (output started at /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php:1079) in /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php on line 1128

Warning: Cannot modify header information - headers already sent by (output started at /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php:1079) in /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php on line 1128

Warning: Cannot modify header information - headers already sent by (output started at /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php:1079) in /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php on line 1128

Warning: Cannot modify header information - headers already sent by (output started at /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php:1079) in /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php on line 1128

Warning: Cannot modify header information - headers already sent by (output started at /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php:1079) in /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php on line 1128

Warning: Cannot modify header information - headers already sent by (output started at /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php:1079) in /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php on line 1128

Warning: Cannot modify header information - headers already sent by (output started at /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php:1079) in /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php on line 1128

Warning: Cannot modify header information - headers already sent by (output started at /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php:1079) in /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php on line 1128

Warning: Cannot modify header information - headers already sent by (output started at /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php:1079) in /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php on line 1128

Warning: Cannot modify header information - headers already sent by (output started at /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php:1079) in /home/p22562/domains/test.biz/public_html/vergadering/fileupload/server/php/UploadHandler.php on line 1128
{"files":[{"name":"compressed.tracemonkey-pldi-09 (2).pdf","size":false,"type":"application\/pdf","error":"File upload aborted","deleteUrl":"http:\/\/test.biz\/vergadering\/fileupload\/server\/php\/index.php?file=compressed.tracemonkey-pldi-09%20%282%29.pdf","deleteType":"DELETE"}]}

What does this mean? Looks like a permission question.

**Comment by hayageek** [comment]
You don't have right permission or upload folder does not exist

**Comment by josvenes** [comment]
i found it the urls have to be in //home instead of http :(
//Jos

Date: Sun, 10 Jan 2016 05:47:31 -0800

**Comment by whittinghamj** [comment]
I've installed this plugin and I'm having some issues which I could really use some help with please.

Its uploading the files but then it errors out with the dreaded error message:

JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

The fact that the files upload suggests its not a permissions issue.

Now I have added some database scripting to the server/php upload file but even taking that out and going back to stock / origional code results in the same issue.

I've checked the network tab but the response is BLANK which is really odd

Any ideas please?

https://www.dropbox.com/s/c0m9z27ku14r2l1/Screenshot%202016-03-29%2005.17.54.png?dl=0
https://www.dropbox.com/s/vj4qcr7zbduh40c/Screenshot%202016-03-29%2005.18.11.png?dl=0
https://www.dropbox.com/s/u9vuygabjupbyqr/Screenshot%202016-03-29%2005.18.24.png?dl=0

But as I said, the files DO upload, my custom DB scripting runs perfectly ...... it just does not send back any results. Very strange indeed.

This is a brand new installed WHM / CPanel server if that makes any difference.

Thanks for any help you can give.

**Comment by hayageek** [comment]
when you set returnType:'JSON'   plugin expects JSON data in the response. but you are returning empty.
https://www.dropbox.com/s/u9vuygabjupbyqr/Screenshot%202016-03-29%2005.18.24.png?dl=0

simple fix, remove returnType option

**Comment by whittinghamj** [comment]
I dont see "returnType' in jquery.fileupload-ui.js

I do however see 'dataType'

I commented out the 'dataType' setting but still got the same error.

Am I having a blonde moment?

thanks

**Comment by hayageek** [comment]
can you share me your URL ? or code ?

**Comment by CarlosJavier81** [comment]
HEllo hayageek, Everything is working good in my laptop with this plugin. Im using xampp apache server. But when i use it in the server, it doesnt work. i use the network tab of chrome and it shows me this, after click upload button:

XMLHttpRequest cannot load http://www.itravel2peru.com/en/upload.php. Response for preflight has invalid HTTP status code 404

is it a server problem? or something could be wrong in the code? Im using 2 files: imageinput.php and upload.php

u can make a test here:

http://itravel2peru.com/en/imageinput.php

**Comment by hayageek** [comment]
There are two issues.

1). Cross domain.
You are acess ing the page using http://itravel2peru.com/en/imageinput.php
non-WWW domain.
but the upload.php url is www.    http://www.itravel2peru.com/en/upload.php

Try to access the page using www.
http://www.itravel2peru.com/en/imageinput.php  it is working.

2).upload.php returns empty.  may be some php errorr, check the server logs.

**Comment by CarlosJavier81** [comment]
Thank you Hayageek. I realized the first mistake. Now i dont have this error on chrome debugger cos i write www in the start.
I dont know what to do with logs, could you help me please?? the upload.php is working ok on my laptop but not in the server.

**Comment by hayageek** [comment]
I think some issue in server, If you can provide me access I can fix it.

**Comment by CarlosJavier81** [comment]
What kind of info do u need?

**Comment by hayageek** [comment]
There is no problem with jquery plugin. Issue may be because of PHP
settings.  If you check the error_log file you will get to know

**Comment by CarlosJavier81** [comment]
How can i check the error_log? i dont know so much about server stuffs ...

**Comment by hayageek** [comment]
check in google.
or provide me server access to me.

**Comment by rajesh09soft** [comment]
Hi Everyone!

My Website is following:

http://rawsunshinecoast.com.au/

During the Checkout page, under your order section, when I clicked on Place Order Button for payment with paypal, its giving me following error:

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

We are using the AWS hosting. 

Will you please help me to sort out this issue. 

Thanks
Rajesh

**Comment by n1ravparmar** [comment]
Hello, i am having same problem, while uploading large files..
