### ISSUE TITLE
Get All Files selected as List<MultipartFile> in upload servlet

### ISSUE THREAD

**Issue by probaner** [hayageek/jquery-upload-file#151]
How is it possible to invoke the upload functionality only once and get all the files as List<MultipartFile> ? The upload servlet is getting invoked as many files are browsed. I need it to be invoked once with all the files selected/browsed. Can you help me on this?

What I am doing:

while using Spring MVC @ModelAttribute. I am having the model which has List<MultipartFile> fileUpload.
I am using autosubmit as false, multiple as true. Every thing is fine. I am able to get Form data, and able to fire upload manually on click of button. But the issue is when user selects multiple file, my model has only 1 file in the List, The Latest file browsed got into the model (List<MultipartFile>).

**Comment by hayageek** [comment]
I Got it. Can you set option serialize: false and try

**Comment by probaner** [comment]
serialize: false is making ModelAttribute List<MultipartFile> as empty. I am using Spring MVC to invoke my controller. So the form data is coming null. This does not solve my problem. I want no matter how many files are selected, the upload controller should be invoked only once.

**Comment by hayageek** [comment]
I think your client code & server code does not match. Did you check the request  in Browser's Network tab ?

Can you share how you are initializing the plugin at client, and how you are handling the files at server side.
