### ISSUE TITLE
parsererror: SyntaxError: JSON.parse: unexpected character at line 2 column 1 of the JSON data 200 OK

### ISSUE THREAD

**Issue by alexandre1973** [hayageek/jquery-upload-file#155]
Hi,

I am trying to populate a jqGrid loading data from a MySQL table named Users. 
The js script looks like this:

JS CODE

$(function () {
        "use strict";
        jQuery("#list2").jqGrid({
			url:'users_grid_load_data.php?q=2', 
			datatype: "json",
            mtype: "GET",			
			colNames:['Id','First Name', 'Last Name', 'Username','Level'], 
			colModel:[ 
			     {name:'id_user',index:'id_user', width:55}, 
				 {name:'firstname',index:'firstname', width:90}, 
				 {name:'lastname',index:'lastname', width:90}, 
				 {name:'username',index:'username', width:90},
				 {name:'level',index:'level', width:80, align:"right"} 	 	 
			], 
			rowNum:10, rowList:[10,20,30], 
			pager: '#pager2', 
			sortname: 'id_user', 
			viewrecords: true, 
			sortorder: "asc", 
			height:"auto",
			width:"auto",
			caption:"LIST OF USERS" 
		}); 
		jQuery("#list2").jqGrid('navGrid','#pager2',{edit:false,add:false,del:false});
    });

PHP FILE

`<?php

$page = $_GET['page']; 
$limit = $_GET['rows']; 
$sidx = $_GET['sidx']; 
$sord = $_GET['sord']; 

if(!$sidx) $sidx =1; 

$result = $mysqli->query("SELECT COUNT(*) AS count FROM users"); 
$row = mysqli_fetch_array($result,MYSQLI_ASSOC); 

$count = $row['count']; 
if( $count > 0 && $limit > 0) { 
    $total_pages = ceil($count/$limit); 
} else { 
    $total_pages = 0; 
} 
if ($page > $total_pages) $page=$total_pages;
$start = $limit*$page - $limit;
if($start <0) $start = 0; 

$SQL = "SELECT * FROM users ORDER BY $sidx $sord LIMIT $start , $limit"; 
$result = $mysqli->query( $SQL ); 

$i=0;
$responce = new stdClass();
$responce->page = $page; 
$responce->total = $total_pages; 
$responce->records = $count;
while($row = mysqli_fetch_array($result,MYSQLI_ASSOC)) {
	$responce->rows[$i]['id']=$row['id_user'];
	$responce->rows[$i]['cell']=array($row['id_user'],$row['firstname'],$row['lastname'],$row['username'],$row['level']);
	$i++;
}

echo json_encode($responce);
?>`

The jqGrid is loaded but in its middle shows the message:

parsererror: SyntaxError: JSON.parse: unexpected character at line 2 column 1 of the JSON data 200 OK {"page":"1","total":1,"records":"1","rows":[{"id":"4","cell":["4","Alexandre","Araujo","alexaraujo73","2"]}]} 

![error](https://user-images.githubusercontent.com/30169094/28200072-cf0d7c3c-6837-11e7-904c-c8fdf834256e.png)

I can see the register loaded from the MySQL table users but I got stuck in this error.
Can anybody help me? I really appreciate any help.
Thank you in advance.

**Comment by alexandre1973** [comment]
php file

`<?php


$page = $_GET['page']; 
$limit = $_GET['rows']; 
$sidx = $_GET['sidx']; 
$sord = $_GET['sord']; 

if(!$sidx) $sidx =1; 

$result = $mysqli->query("SELECT COUNT(*) AS count FROM users"); 
$row = mysqli_fetch_array($result,MYSQLI_ASSOC); 

$count = $row['count']; 
if( $count > 0 && $limit > 0) { 
    $total_pages = ceil($count/$limit); 
} else { 
    $total_pages = 0; 
} 
if ($page > $total_pages) $page=$total_pages;
$start = $limit*$page - $limit;
if($start <0) $start = 0; 

$SQL = "SELECT * FROM users ORDER BY $sidx $sord LIMIT $start , $limit"; 
$result = $mysqli->query( $SQL ); 

$i=0;
$responce = new stdClass();
$responce->page = $page; 
$responce->total = $total_pages; 
$responce->records = $count;
while($row = mysqli_fetch_array($result,MYSQLI_ASSOC)) {
	$responce->rows[$i]['id']=$row['id_user'];
	$responce->rows[$i]['cell']=array($row['id_user'],$row['firstname'],$row['lastname'],$row['username'],$row['level']);
	$i++;
}

echo json_encode($responce);
?>`

**Comment by hayageek** [comment]
Chek the response in the browser Network tab, looks like response is not
JSON.  May be some php warnings in the response
