### ISSUE TITLE
Upload Zip File

### ISSUE THREAD

**Issue by aditya1122** [hayageek/jquery-upload-file#156]
I am trying to upload zip file but it is not uploading.

    uploadgis = $("#upload_shape_file").uploadFile({
     url: serverpath + "api/Service/GISFileUpload",
     fileName: "myfile",
     showDone: true,
     allowedTypes: "zip",
     acceptFiles: ".zip",
    multiple: false,
    dragDrop: false,
    autoSubmit: false,
    showProgress: true,
    showStatusAfterSuccess: false,
    onSuccess: function (files, response, xhr, pd) {
        alert("success");
    },
    onError: function (files, status, errMsg, pd) {
        alert("fail");
    }

    });

**Comment by hayageek** [comment]
Can you share your server code, how you are handling the file.

**Comment by aditya1122** [comment]
solved the issue as there was a problem in the server code
