### ISSUE TITLE
upload multiple files

### ISSUE THREAD

**Issue by 185365936** [hayageek/jquery-upload-file#157]
If I upload multiple files, there will be multiple requests to the server. Can I upload multiple files with only one request?

**Comment by hayageek** [comment]
set option  serialize:false

**Comment by 185365936** [comment]
Thanks for your help,  but it's wrong...
![picpick20170801120341](https://user-images.githubusercontent.com/12274638/28808921-61953fbc-76b2-11e7-97e1-645f894bcb32.jpg)
![picpick20170801120440](https://user-images.githubusercontent.com/12274638/28808920-6191b270-76b2-11e7-98ef-01b539a119e7.jpg)

**Comment by hayageek** [comment]
What is the plugin version ?
If possible , can you share your URL ?

**Comment by 185365936** [comment]
Sorry, I have been preparing demo and server. This is a java project and the plugin is latest version.
I only know a little bit of English.
The expression is unclear.
This demo if I upload multiple files, there will be multiple requests to the server.
My purpose is to upload multiple files at once, and only request the server once.
![image](https://user-images.githubusercontent.com/12274638/29001363-61b740f0-7abb-11e7-8c89-bb94caa81fee.png)
How do I set the option?
url : http://www.huanglei936.cn
source: https://gitee.com/hlmilies/webjsp
Thank you very much.

**Comment by aditya1122** [comment]
when i set serialize to false then i don't get the form data  at the server code

**Comment by yangzongjin** [comment]
Hello, how was it ultimately resolved?
