### ISSUE TITLE
filename turn to gash code when uploading file with Chinese name.

### ISSUE THREAD

**Issue by kisssg** [hayageek/jquery-upload-file#158]
hi,dear,

filename turn to gash code when uploading file with Chinese name. 
Hope you can repair it.

**Comment by hayageek** [comment]
can you send me the  filename.

**Comment by kisssg** [comment]
'厨柜.xlsx', it becomes '鍘ㄦ煖.xlsx' on the server side folder. 
I am using the latest php version. 
Thanks a lot~~
