### ISSUE TITLE
3.1.10: Android/Opera/Chrome: can not upload photo chosen from gallery

### ISSUE THREAD

**Issue by hq9000** [hayageek/jquery-upload-file#161]
With this plugin, on some Android devides we can not upload photos chosen from the "Gallery". When choosing photo another way (let's say taking a new picture with camera) everything works fine.

**Comment by hayageek** [comment]
are u using webview ?

Opening the webpage directly in browser ?  which browser ?  did you see any request coming to server ?

**Comment by igorevteev** [comment]
From phone Xiaomi MIUI 8.6 in Google Chrome 59.0.3071.125 and Opera.

**Comment by igorevteev** [comment]
[http://prntscr.com/gbpx33](url)

**Comment by igorevteev** [comment]
version 3.1.10 - crashes the whole page
version 4.0.10 - [not load`](url
![image](https://user-images.githubusercontent.com/14041497/29579428-839644f6-877b-11e7-89d0-bf4c9257d5e4.png)
)

**Comment by igorevteev** [comment]
in debug mode:
-coming in function onSelect
-i'm wait on breakpoint
-after 6-7 sec - crash browser

**Comment by igorevteev** [comment]
https://drive.google.com/open?id=0B5Yk_R7l0ncRNFhtdUVfbjJacHM

**Comment by hq9000** [comment]
1. we are using browser (at least Chrome is known to have this problem)
2. initially, we saw the browser crashing completely shortly after having selected a picture from the gallery
3. then we tried to remove our google tag manager code which was loading some tracking js. It helped, the browser seems to crash less frequently  and we sometimes actully see the request to server in the console.
4. however, the request is "cancelled". Please see the screenshot

http://prntscr.com/getufb

* on some android devices we've tested it with everything works fine.

**Comment by hayageek** [comment]
What is the response for the request in the screenshot

**Comment by hq9000** [comment]
There is no response, it looks like the browser doesn actually send it.

**Comment by hq9000** [comment]
We now have some evidence that this might be not the plugin issue.  So  we closing this bug and create another one:

https://bugs.chromium.org/p/chromium/issues/detail?id=762505

thanks for your time and responses
