### ISSUE TITLE
upload multiple files

### ISSUE THREAD

**Issue by aditya1122** [hayageek/jquery-upload-file#163]
If I upload multiple files, there will be multiple requests to the server. Can I upload multiple files with only one request and dynamic formdata?

    $("#upload_ts_dfs0").uploadFile({
                        uploadStr: "Select Timeseries",
                        url: udrdb_serverpath + "api/Service/TimeseriesDfs0FileUpload",
                        fileName: "myfile",
                        showDone: true,
                        allowedTypes: "dfs0",
                        acceptFiles: ".dfs0",
                        multiple: true,
                        dragDrop: false,
                        autoSubmit: false,
                        showProgress: true,
                        showStatusAfterSuccess: true,
                        sequential: true,
                        sequentialCount: 1,
                        uploadButtonClass: "btn btn-default",
                        showCancel: true,
                        showAbort: false,
                        showFileCounter: true,
                        serialize: false,
                        showFileSize: true,
                        dynamicFormData: function () {
                            selectedLayerId = $("#uploadFeatureAssociatedTimeseriesDfs0PopupForm2 #selected_layer_id").val();
                            selectedFeatureId = $("#uploadFeatureAssociatedTimeseriesDfs0PopupForm2 #selected_feature_id").val();

                            var data = {
                                featureClassId: selectedLayerId,
                                featureId: selectedFeatureId
                            }
                            return data;
                        },
                        onSelect: function (files) {
                            uploadTsDfs0Obj.cancelAll();
                            $(".ajax-file-upload-container").show();
                            $footerButton.enable();
                            return true;
                        },
                        onCancel: function (files, pd) {
                            if ((uploadTsDfs0Obj.selectedFiles - files.length) === 0) {
                                $footerButton.disable();
                                $(".ajax-file-upload-container").hide();
                            }
                        },
                        onSuccess: function (files, response, xhr, pd) {
                            featureAssociatedTimeseriesDfs0FileImportDialog.close();
                        },
                        onError: function (files, status, errMsg, pd) {
                            featureAssociatedTimeseriesDfs0FileImportDialog.close();
                            bootbox.alert(errMsg);
                        }
    });

The data is collected in the data object in dynamicFormData option but data is not received in server code. If I put serialize: true then, multiple request are sent to the server.

**Comment by hayageek** [comment]
Go the issue.
get this js file,  http://hayageek.com/docs/test.js

**Comment by aditya1122** [comment]
The issue is not solved yet.

**Comment by hayageek** [comment]
can you share me your URL ?

**Comment by aditya1122** [comment]
the issue is solved. i had to put the object in the formdata and then pick the dynamic formdata with the same object name.
