### ISSUE TITLE
Multi uploads to PHP

### ISSUE THREAD

**Issue by jochen1727** [hayageek/jquery-upload-file#164]
Hi,
First thks for your plug in :-) Great job.
I m a newbie, i have a trouble :-)
I d like to send my files from the file button and attach them to send them through php with phpmailer.
I have tried without your plug in and i can receive them on my mailbox but don't work with your :'( .
your plug in send via $_FILES variable?

Thks

My Html

`<div id="fileuploader">Upload</div>`

My java code 

`$(document).ready(function()
{
	$("#fileuploader").uploadFile({
	url:"mail.php",                                      //My php file
	fileName:"myfile",
    multiple:true,
    dragDrop:true,
    sequentialCount:1,
        showPreview:true,
 previewHeight: "100px",
 previewWidth: "100px",
	});
});`

My php to attach multiples files via $mail->addattachment

`for ($ct = 0; $ct < count($_FILES['userfile']['tmp_name']); $ct++) {
        $uploadfile = tempnam(sys_get_temp_dir(), hash('sha256', $_FILES['userfile']['name'][$ct]));
        $filename = $_FILES['userfile']['name'][$ct];
        if (move_uploaded_file($_FILES['userfile']['tmp_name'][$ct], $uploadfile)) {
            $mail->addAttachment($uploadfile, $filename);
        } else {
            $msg .= 'Failed to move file to ' . $uploadfile;
        }
    }`

**Comment by hayageek** [comment]
You are setting the option fileName:"myfile", 

but you are accessing the files using  $_FILES['userfile'], that is the issue.

so change fileName:"userfile",

**Comment by jochen1727** [comment]
Thks to reply quicly, i ve already tried and changed named "userfile" but nothing append :'(.
May i add some options to pass my files to the php page ?
Thks hayageek

**Comment by jochen1727** [comment]
When i upload my file through a classic file button and send them to my php that work fine.
As you said i ve changed file name but nothing happend that while i guess i ve miss an option ?

**Comment by jochen1727** [comment]
I ask me something.
The button file upload send files to my php page but i have a form submit button which send form input to my php page.
Is it possible that when i upload file it sent to my php page in same time submit button send to my php page. I thinks that issue are they don't send in the same time data?
I m a newbie and don't know how do it?
Thks.

**Comment by hayageek** [comment]
Option 1) you can send form data with the file,
Check formData, dynamicFormData() options

Option 2)After the uploading is finished, you can send some data to your
server.
Check afterUploadAll() callback

**Comment by jochen1727** [comment]
ok,
I would like upload files with my $_FORM when i click on the submit file instead send them now.
Could you tell me how do that?
Thks
