### ISSUE TITLE
The uploader uploads more than one file

### ISSUE THREAD

**Issue by costa100** [hayageek/jquery-upload-file#166]
Hi:

I am using version 3.1.0 in conjunction with angular. I have an interesting scenario reported by the tester in Chrome:

1. Click the Browse button to select a file
2. Select the file
3. Click the Browse button again and select another file
4. Click Upload. Both files are uploaded even though multiple is set to false.

Code:

```
var e = element.find('#fileuploader');
e.uploadFile({
  //var settings = {

  url: appBaseUrl + "api/v1/Action/" + $scope.Id,
  method: "POST",
  allowedTypes: $scope.attachmentFileExtensions,
  maxFileSize: $scope.attachmentMaxFileSizeInBytes,
  maxFileCount: 1,
  fileName: "myfile",
  multiple: false,
  dragDrop: false,
  maxNumberOfFiles: 1,
  showFileCounter: false,
  showProgress: true,
  autoSubmit: false,
  dynamicFormData: function () {
    return {CategoryId: $scope.CategoryId};
  },
  onSuccess: function (files, data, xhr) {
    element.find('#status').html("<font color='green'>Upload  was successful</font>");
    //   $("#status").html("<font color='green'>Upload " + data + "is success</font>");
  },
  onError: function (files, status, errMsg) {
    element.find("#status").html("<font color='red'>Upload has Failed</font>");
    //  $("#status").html("<font color='red'>Upload is Failed</font>");
  }
});
element.find('#btnfp').click(function () {
  e.startUpload();
});
}
```
      
Is this still an issue in the newer version?

Thank you

**Comment by costa100** [comment]
Just writing again, yes, it is still an issue with in 4.0.11. If you set:

```
sequential: true,
sequentialCount: 1,

```
and follow the steps above you upload two files not only one as you might think.

**Comment by costa100** [comment]
I hacked version 3.1.0 and I added:
```
            	  $("." + obj.formGroup).each(function (i, items) {
                  if ($(this).is('form')) $(this).remove();
                });
```

in serializeAndUploadFiles just before the form variable is set.

Honestly, I had a hard time following the code. If I may give you a suggestion, can you please use variables that are longer than s, ts, obj? I still don't understand why all those temp forms are created. Actually there are two sets of forms created, the ones that have an input type="file" in them and these forms which are actually submitted. Why is this done? I assume there is a reason.

Thanks

**Comment by hayageek** [comment]
s -> settings
ts -> temp settings
obj -> object

temp forms are created for old browsers.  old browsers don't support File object, using form submit for uploading.

**Comment by hayageek** [comment]
BTW, current version is 4.0.11
