### ISSUE TITLE
The script counts the uploaded files so I can't upload another files !!!

### ISSUE THREAD

**Issue by PhpMax** [hayageek/jquery-upload-file#169]
Hello,
When using Show previous uploads feature and setting maxFileCount:3 for example and try uploading more files I got error message "... is not allowed. Maximum allowed files are:3" It seems the script counts the already uploaded files so I can't upload another files !!!

![snapshot2](https://user-images.githubusercontent.com/1113048/31287568-64f60708-aaca-11e7-9867-dddd3994168b.png)

**Comment by RajcsanyiZ** [comment]
I have a similar problem. When I upload an invalid file the counter doesn't decrease.

My solution is that:

```javascript
var uploadAttachment = $('#attachment2').uploadFile({
          onSuccess: function(files,data,xhr,pd)
            {
                // it was a failure
                if (!data.success) {
                    pd.statusbar.hide();
                    pd.statusbar.remove();
                    uploadAttachment.selectedFiles--;
                }
            },
});
```

You must reset the counter:
```javascript
  var uploadAttachment = $('#attachment2').uploadFile();
  uploadAttachment.selectedFiles=-1;
```

**Comment by hayageek** [comment]
don't set  maxFileCount. it will work
