### ISSUE TITLE
Double ajax

### ISSUE THREAD

**Issue by ducvu91** [hayageek/jquery-upload-file#173]
Hi,
All work fine, but i have issue, i upload one file, after select file, it double ajax call to server. 
![screenshot_2](https://user-images.githubusercontent.com/19793530/33473689-01209638-d6aa-11e7-9d6b-35717f89f575.png)

First request didn't have data, request 2 have data that is my need. How to config only get request  ajax ?
Thanks.

**Comment by hayageek** [comment]
did you select 2 files ?
can you share your code ?

**Comment by ducvu91** [comment]
Thanks you reply !
My code
`<a id="fileuploader" href="javascript:void(0)" title="">
                                {{--<a id="uploadFile1" href="javascript:void(0)" title="">--}}
                                    <i class="fa fa-plus" aria-hidden="true"></i>
                                    <span>Hãy tải video clip quay lại hình ảnh bạn đang thực hiện thử thách vui khỏe từ Nestlé để tạo ảnh nhé.</span>
                                </a>`
var uploadObj = $("#fileuploader").uploadFile({
	url: myurl,
	multiple:false,
	dragDrop:false,
	maxFileCount:1,
	fileName:"myfile",
	previewWidth: "auto",
	uploadStr: _str,
	onSelect:function(files)
	{
		//some code check file type and size

		var data = new FormData();

		$.each(files, function(key, value)
		{
			data.append('videoUpload', value);
		});
		uploadObj.formdata = data;
		return true; //to allow file submission.
	},
	onSubmit:function(files)
	{
		$('#fade').show();
	},
	onSuccess: function(files, data, xhr, pd) {
		if(data.error)
		{
			$('#fade').hide();
			alert(data.message);
			location.reload();
		}
		else
		{
			var myData = data.data;
			//ajax if success
		}

	},
	onError: function(files,status,errMsg,pd) {
		$('#fade').hide();
		alert(errMsg);
		location.reload();
	},
	onAbort: function() {
		console.log('1');
	},
	deleteCallback: function(data, pd) {
	}
});

**Comment by hayageek** [comment]
code is right, it should not give any problem.
did you see the request in the browser ? is it sending the same file twice ?

**Comment by antonito82** [comment]
Same issue happened to me with 4.0.5 version.  This issue is not happen in 4.0.11 version.

Why the latest tag is 4.0.2?

**Comment by hayageek** [comment]
Demo page also having version 4.0.11  http://hayageek.com/docs/jquery-upload-file.php

**Comment by antonito82** [comment]
Con BOWER, la última versión para descargar es la 4.0.2
Y con NPM, la última versión para descargar es la 4.0.5
Como me descargo la 4.0.11? A manija?

**Comment by hayageek** [comment]
updated npm version.
