### ISSUE TITLE
On Single Page Show Two File Uploaders

### ISSUE THREAD

**Issue by hassanuos** [hayageek/jquery-upload-file#174]
Hey @hayageek 
is there any option we can show two file uploaders div tags. I check this but no success.  I want one the top of the page and one on the bottom of the page. Like this

<div id="fileuploader">Upload</div>
<div id="fileuploader">Upload</div>

When I use this Only one of them get a proper design and the second one is broken. It will be great help if you could provide any solution. Thanks in advance.

**Comment by hayageek** [comment]
div id="fileuploader1">Upload</div>

<div id="fileuploader2">Upload</div>

$("#fileuploader1,fileuploader2").uploadFile({
url:"YOUR_FILE_UPLOAD_URL",
fileName:"myfile"
});

**Comment by hayageek** [comment]
check the "Features" tab, http://hayageek.com/docs/jquery-upload-file.php#customui

it have many upload buttons.
