### ISSUE TITLE
How to make wide the Drag Div ?

### ISSUE THREAD

**Issue by dungla2011** [hayageek/jquery-upload-file#175]
How can make Drag zone wide more, like google drive for example ?
(and drag zone include file list...)

![image](https://user-images.githubusercontent.com/7878963/33939934-a10be4d8-e03f-11e7-9227-f0efc976d2b4.png)

Thank you!

**Comment by hayageek** [comment]
you can change the style of the dragdrop div.

on your can have your own class

set this option:
dragDropContainerClass:  "ajax-upload-dragdrop",

**Comment by dungla2011** [comment]
thank you, but it not work, like in this image:

![Uploading image.png…]()

**Comment by hayageek** [comment]
by default
dragDropContainerClass: "ajax-upload-dragdrop",

change the class `ajax-upload-dragdrop` style in CSS
