### ISSUE TITLE
100% Progress Bar on Failed Uploads

### ISSUE THREAD

**Issue by rajsubhag** [hayageek/jquery-upload-file#177]
Hi,

I have a strange issue, the progress bar goes 100% even if the upload fails. I validate the allowed files types at back end.

I believe the plugin assumes that a successful upload has been done if it receives a response from the server.

How can we make the progress bar 0% when backend validation fails.

Regards
Raj
![failed](https://user-images.githubusercontent.com/36650542/36403260-91a5252e-162f-11e8-86f4-5cdfc9153260.PNG)

**Comment by hayageek** [comment]
onSuccess: function (files, response, xhr, pd) {

//You can control using PD
pd.progressDiv.show();
pd.progressbar.width('0%');

},

**Comment by hayageek** [comment]
You can restrict the filetype at client side also using the below options.

allowedTypes:"jpg,png,gif,jpeg,bmp,tiff"
acceptFiles: "image/*",
