### ISSUE TITLE
set formData while onLoad being invoked

### ISSUE THREAD

**Issue by probaner** [hayageek/jquery-upload-file#181]
I need to show previously loaded images in my page. I am able to accomplish it using
onLoad:function(obj). But I also need to populate some formData which I need to send while deleting. How to achieve this?

**Comment by hayageek** [comment]
In deleteCallback you have the value

deleteCallback:function(data, pd)
{

}
where data, is the returned object in onLoad method.

**Comment by probaner** [comment]
Thanks. I got it. But another question. When is onError function invoked? Suppose I want to stop file upload and show some message what jeno data I must send from server. I saw 'customErrorMessage' but how to let the client know file upload has failed.

**Comment by probaner** [comment]
Thanks. I got it. But another question. When is onError function invoked? Suppose I want to stop file upload and show some message what json data I must send from server. I saw 'customErrorMessage' but how to let the client know file upload has failed.

**Comment by hayageek** [comment]
onError() is called in two scenarios,
1).if the upload is failed,
2).if the upload is success, but if you return the custom error.
