### ISSUE TITLE
Problems with mp3 files

### ISSUE THREAD

**Issue by Udirley** [hayageek/jquery-upload-file#183]
Guys, is there any limitation that could prevent the working for mp3 files?
For wav files works correctly, for mp3 does not show any error, however the file is not imported.
I am using the latest version of plugin 4.0.11.
Thanks for any help.

**Comment by hayageek** [comment]
It is not the problem with plugin, it should be with server.  what is the mp3 file size.
In the browser network, you can see the response code and check at server.

**Comment by Udirley** [comment]
Thanks for the answer, the problem really was in limiting the size of the file in php.ini, the mp3 file exceeded the maximum size allowed.
