### ISSUE TITLE
reloading failed files

### ISSUE THREAD

**Issue by roghellman** [hayageek/jquery-upload-file#188]
Similar to if not identical to another question still unanswered.

I use the onSubmit to scan all of the pending files, in particular I ensure that a required field in the extraHTML has data entered.  If not, I give that field a background that suggests an error.

This works well.  But once those fields have been completed the submit button does nothing.  How can I reset it without having to load the files again into the pending status?

**Comment by hayageek** [comment]
i did not understand it , can you show sample code.and exact issue.

**Comment by roghellman** [comment]
I'm sorry Ravishanker.  I found a work around and this is no long an issue
for me.

I was trying onSubmit()to ensure that some dynamic html input fields had
been filled out.  When they weren't it stopped their upload (as intended)
but once I had placed values in those fields the submit button would not do
anything.


Rogers
