### ISSUE TITLE
Order of files

### ISSUE THREAD

**Issue by ludwiczakpawel** [hayageek/jquery-upload-file#20]
How can I change order of files in uploaded files listing? Currently new files are added to the bottom of list. I'd like them to have on top of the list. Is there any way to do that?

**Comment by dungla2011** [comment]
it's better if we have one option for this, because I think it's also basic option :)

**Comment by hayageek** [comment]
already there is an option uploadQueueOrder:'top'    or  'bottom'

**Comment by dungla2011** [comment]
Great! It is work now!
But I not see it in docs:
![image](https://user-images.githubusercontent.com/7878963/35773414-3d13455c-0984-11e8-81fd-50ecfcf0cff8.png)
