### ISSUE TITLE
IE8 'nestedForms: false'

### ISSUE THREAD

**Issue by gameison** [hayageek/jquery-upload-file#29]
jquery.uploadfile.js 111 line:

var uploadLabel = $('&lt;div&gt;' + $(this).html() + '&lt;/div&gt;'); // not work

var uploadLabel = $('&lt;label&gt;' + $(this).html() + '&lt;/label&gt;'); // work. also IE11 and chrome

**Comment by hayageek** [comment]
Fixed in latest plugin.
