### ISSUE TITLE
onError doesn't fire on 404 or 500 server status

### ISSUE THREAD

**Issue by wesww** [hayageek/jquery-upload-file#41]
there's no way to handle failed uploads, is this the only error function?
`onError: function() { }`

If the goal for that function is only outputting a message sent with a 200 status, you might consider adding a function for onFail

**Comment by hayageek** [comment]
Hi
onError is called for 404 , check this demo:
http://hayageek.com/examples/jquery/jquery-multiple-file-upload/testbed/showerror.php
upload any file and see
