### ISSUE TITLE
Do any functions fire on maxFileSize over limit?

### ISSUE THREAD

**Issue by zocheyado** [hayageek/jquery-upload-file#45]
I am trying to have some custom wording / events happen when a user tries to upload over the max file size. Currently as far as I can tell you can only edit the string that gets sent back when this happens. Is there a function that fires this event? If so which one

**Comment by hayageek** [comment]
No callback for maxFile reach

**Comment by Nadeem2462** [comment]
Is there any way to trigger an error when file size exceeded the limit
