### ISSUE TITLE
File upload not working 

### ISSUE THREAD

**Issue by webmaster-jhon** [hayageek/jquery-upload-file#46]
Hi
Thanks for your plugin. I've used this plugin many times before and it worked very well. But as of now, I've an upload script on backend which works smoothly. But when I try to use same script (copy) on frontend file upload doesn't work at all.

Instead of uploading file it sends two ```POST``` requests and calls ```onError()``` callback. After calling callback, it ```redirects``` me to another page (i.e. file upload URL).

Thanks in advance.

Regards
John Smith

**Comment by hayageek** [comment]
Upload handler and front end are in different domains?
