### ISSUE TITLE
replacing upload instead of append

### ISSUE THREAD

**Issue by vishnuc** [hayageek/jquery-upload-file#47]
After setting maxfile count to 1, when we upload more than 1 images  , Currently it displays error.But instead showing error how to replace the image and upload new without appending progressbar and file name.

**Comment by hayageek** [comment]
You need  to customize . Put your requirements in Paintbrush, send me. I will customize for you

**Comment by DanielSantanaRibeiro** [comment]
Hi
how to customize to always replace file ? 
Using the onSelect callback ?
