### ISSUE TITLE
Show Thumb after upload

### ISSUE THREAD

**Issue by mgk89** [hayageek/jquery-upload-file#49]
Hi,
I'm creating a thumbnail by the upload.php

Due to the scrolling issues with the preview function I would like to show the generated thumbnail on the same place as the preview thumb is shown, right after each thumbnail is created.

How would that be possible?
thank you verymuch!

**Comment by hayageek** [comment]
onSuccess:function(files,data,xhr,pd)
{
    //files: list of files
    //data: response from server
    //xhr : jquer xhr objec

pd.preview.html("<img src='"+data[0]+"' />");

}

**Comment by mgk89** [comment]
hello,

can you explain that a little bit more in detail? my js knowledge is not very good. thank you!

**Comment by hayageek** [comment]
Hi,
Check this demo:
http://hayageek.com/examples/jquery/jquery-multiple-file-upload/testbed/showPreview.php

**Comment by mgk89** [comment]
hi,

thank you for your answer! unfortunately it didn't work the way I would like to.

What I do have is showpreview=true to show the preview of older uploaded images.

to avoid the scrolling issues and the crashing of chrome I don't want to show the preview while the images is uploaded. it would be perfect if there was a 99x99 px placeholder image foreach image that is beeing uploaded.

after the upload is finished the src of the placeholder should be changed to the new thumbnail (which i already could do)

so my problem is: how to not show preview of the pictures that are selected for upload, but still show preview of old pictures that are already uploaded and show for the pictures that are still on progress a placeholder?

thank you very much for your time!

**Comment by mgk89** [comment]
hi,

it's me again.

I could do what I asked by changing the .js

There is just one littel issue left:

I need to get back the changed file name from the upload.php to the index.html for

	onSuccess:function(files,data,xhr,pd)
	{
	
		pd.preview.attr("src","http://www.-----.com/gallery/thumbs/"+files[0]);

	}

to show the thumbnail after it is generated. But files[0] just returns the original file name, but the thumbnail is named just as the uploaded image is renamed in the upload.php

Do you know what I mean? Thank you for your help!!!
