### ISSUE TITLE
readme doc's "showPreivew" is wrong.

### ISSUE THREAD

**Issue by wentmac** [hayageek/jquery-upload-file#50]
readme doc's "showPreivew" is wrong.
![qq 20150406182136](https://cloud.githubusercontent.com/assets/3828820/7003579/7eb5c932-dc8f-11e4-8f61-9ea0ba412d78.png)

**Comment by hayageek** [comment]
Thanks. I have updated

**Comment by wentmac** [comment]
http://hayageek.com/docs/jquery-upload-file.php IE is not working,[IE6,IE7,IE8,IE9,IE10]
![qq 20150407141231](https://cloud.githubusercontent.com/assets/3828820/7017864/46b05042-dd30-11e4-86d1-3495bdfb4896.png)
