### ISSUE TITLE
Option to set global: false

### ISSUE THREAD

**Issue by fabriziomazzoni** [hayageek/jquery-upload-file#53]
I cannot find an option to set the global ajax variable to false. This would be useful if someone is using ajaxStart and ajaxStop methos for spinners etc in order to avoid them to fire when this plugin is used.

**Comment by hayageek** [comment]
but what you want to set in the plugin ? can you elaborate ?

**Comment by fabriziomazzoni** [comment]
I suppose there is an ajax call in the plugin as on my website the ajaxStart function is firing.
In order to control the behaviour of $.ajax, as per documentation in jquery API, there is a variable called "global". If this is set to false, the ajaxStart event will not fire. This can be very useful.

**Comment by howardhee** [comment]
Closed means solved? I have same issue, how to solve it?

**Comment by hayageek** [comment]
Can you please explain bit more what exactly you want, I will make the
changes .

**Comment by howardhee** [comment]
When I upload the image, the ajax is fired, and the loading panel is overlay whole page, that make me unable to click "Abort" button to stop upload. What I want is just trigger loading panel when delete button is click. So I need stop the ajax by set the "global:false" when upload button click. I found the original jquery api have that option, but not working in your plugin.
