### ISSUE TITLE
Translate labels

### ISSUE THREAD

**Issue by Rudloff** [hayageek/jquery-upload-file#54]
It would be useful to have a way to customize/translate button labels.

**Comment by hayageek** [comment]
Hi,
You can do it. check "Advanced" Tab in
http://hayageek.com/docs/jquery-upload-file.php

dragDropStr: "<span><b>Faites glisser et déposez les fichiers</b></span>",
abortStr:"abandonner",
cancelStr:"résilier",
doneStr:"fait",
multiDragErrorStr: "Plusieurs Drag & Drop de fichiers ne sont pas
autorisés.",
extErrorStr:"n'est pas autorisé. Extensions autorisées:",
sizeErrorStr:"n'est pas autorisé. Admis taille max:",
uploadErrorStr:"Upload n'est pas autorisé"

**Comment by Rudloff** [comment]
Oh, sorry, I didn't see that (I was looking at README.md).
