### ISSUE TITLE
Upload large files

### ISSUE THREAD

**Issue by markknochen1** [hayageek/jquery-upload-file#56]
Hello, 

i can upload files to 200 MB ... over this size i get no response and if the upload is canceled, the message from Firebug:

jquery upload SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Server-Options are:

php_value post_max_size 2000M
php_value upload_max_filesize 2000M
php_value memory_limit 4000M

What is wrong?

Thank you

Mark

**Comment by hayageek** [comment]
issue is solved ?

**Comment by markknochen1** [comment]
No ... i get always the error "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data" by uploading files over 300MB

**Comment by hayageek** [comment]
which browser ? I will reproduce the issue.

**Comment by markknochen1** [comment]
I use the current Version of Firefox .... i saw the error in FireBug .....

**Comment by hayageek** [comment]
Hi My server upload max size is: 100 MB. i can able to upload max 100 MB. to check the error, can you check in chrome. it gives "Request Entity Too Large".

**Comment by markknochen1** [comment]
Yes. but my server options are:

php_value post_max_size 2000M
php_value upload_max_filesize 2000M
php_value memory_limit 4000M

so i should upload a file with 2000M ... or at least 1000MB

**Comment by hayageek** [comment]
that's true. but can you try to upload in chrome and see the error.

**Comment by hayageek** [comment]
Did you try in chrome.chromes gives proper error

**Comment by markknochen1** [comment]
mh, now i can upload for test 600 MB without problems ….

falk

Am 17.07.2015 um 14:52 schrieb Ravishanker Kusuma <notifications@github.com>:
