### ISSUE TITLE
Show thumbnail immediately after upload

### ISSUE THREAD

**Issue by mgk89** [hayageek/jquery-upload-file#58]
hello,

just a litte thing:

    onSuccess:function(files,data,xhr,pd)
    {
    pd.preview.attr("src","http://www.foo.bar/php4/uploads/<? echo $album; ?>/thumbs/"+files[0].toLowerCase());
    	}
[/code]

is supposed to change a symbol image (one preload image for all uploads) to the created thumbnail.

that actually just works immediately if there are less than 7 pictures selected for upload. If you select a larger amout of pictures for upload, the thumbnails will be shown when ALL uploads are finished (although the correct source of the thumbnail is already shown in the source code).

Do you know what I mean?

Thank you for your advice!!!

**Comment by hayageek** [comment]
Get latest plugin
