### ISSUE TITLE
Example 7 seem to send file twice

### ISSUE THREAD

**Issue by atorkhov** [hayageek/jquery-upload-file#61]
Example 7 with separate "start upload" button at hayageek.com seem to send file twice

**Comment by hayageek** [comment]
Twice means, is it sending two requests ? It is expected. If you select N
files, it will send N requests, to get the progress for each file

**Comment by atorkhov** [comment]
Yes, two requests. But for one file.

**Comment by hayageek** [comment]
But i have checked just now. I am seing only one request. Which browser did
you try ? can you share your UR ?

**Comment by atorkhov** [comment]
I'm using Firefox 39. I've attached screenshots with firebug and details of requests. What is UR btw?

![upload1](https://cloud.githubusercontent.com/assets/495108/8902311/5c4a5a2c-3458-11e5-9d78-4fe567aa0457.png)
![upload2](https://cloud.githubusercontent.com/assets/495108/8902319/64dc028a-3458-11e5-93c5-67bd07f74282.png)

**Comment by hayageek** [comment]
Fixed down. V 4.0.2
