### ISSUE TITLE
afterUploadAll not working as expected

### ISSUE THREAD

**Issue by Amadeus-** [hayageek/jquery-upload-file#64]
Here is the file that I'm working with for testing right now:  https://gist.github.com/Amadeus-/aeb88c623eab08031347      ...Everything seems to be working exactly right (and exactly how I expect), except for the afterUploadAll event never seems to fire.   I don't see it firing if I upload just one file or several files simultaneously.

Is it possible that the afterUploadAll event doesn't fire if autoSubmit is false?

(I am in the process of learning your jquery and your jquery plugin simultaneously, so please don't judge my ugly script test script!)

**Comment by folksy** [comment]
Hello,

Thank you for contacting Folksy Support. We aim to respond to
queries within one working day but we will get back to you as
soon as possible.

Our standard Support hours are 9am GMT/BST to 5pm GMT/BST
Monday-Friday.

Please note that we offer limited support at the weekends and on
UK Bank Holidays:

https://www.gov.uk/bank-holidays ( https://www.gov.uk/bank-holidays )

While you are waiting, please take a look at our Knowledge Base
for answers to our most frequently asked questions:

http://folksy.uservoice.com/knowledgebase ( http://folksy.uservoice.com/knowledgebase )

If your enquiry relates to a service-critical issue out of office
hours (e.g. your shop has been restricted and you are unable to
process orders), please email us at urgent@folksy.co.uk (
mailto:urgent@folksy.co.uk )

Thank you,

Folksy Support

-----

Email: support@folksy.com ( mailto:support@folksy.com )

Helpdesk (buyer and seller FAQs): http://folksy.uservoice.com/ ( http://folksy.uservoice.com/ )

Blog (including seller tips): http://blog.folksy.com ( http://blog.folksy.com )

Forums (talk to our community): http://talk.folksy.com ( http://talk.folksy.com )

On September 07, 2015 at 3:52 AM hayageek/jquery-upload-file
wrote:

Here is the file that I'm working with for testing right now:
https://gist.github.com/Amadeus-/aeb88c623eab08031347 ( https://gist.github.com/Amadeus-/aeb88c623eab08031347 )
...Everything seems to be working exactly right (and exactly how
I expect), except for the afterUploadAll event never seems to
fire. I don't see it firing if I upload just one file or
several files simultaneously.

Is it possible that the afterUploadAll event doesn't fire if
autoSubmit is false?

(I am in the process of learning your jquery and your jquery
plugin simultaneously, so please don't judge my ugly script test
script!)

---

Reply to this email directly or view it on GitHub:

https://github.com/hayageek/jquery-upload-file/issues/64 ( https://github.com/hayageek/jquery-upload-file/issues/64 )

Powered by UserVoice. ( http://www.uservoice.com/powered-by?utm_campaign=poweredby&utm_medium=email&utm_source=ticket&uv_company=Folksy&uv_contact_url=folksy.uservoice.com&uv_experience=email )

**Comment by hayageek** [comment]
Hi,
Can you host the files and send me the URL ?
validation is working fine in the form ?

Check this . it is working in my website. I have removed validation logic.

http://hayageek.com/examples/jquery/jquery-multiple-file-upload/testbed/one.html

**Comment by Amadeus-** [comment]
Thank you so much for looking into it.

I have it hosted at http://maestro.isxgames.com/test/ currently.   The validation (and the uploading) all work as far as I can see, and I'm not seeing any errors in the Chrome "inspect element" console, etc.   The only thing that is problematic, is that one event.

I do see that it works on your version -- hopefully it will be obvious what is causing the problem.   If you need to see the upload.php I'm using, it's at http://maestro.isxgames.com/test/upload.txt    I really haven't done much with it yet other than testing things, so it's pretty much your sample plus a bunch of as-yet unused variables.

Also, rather than open another issue, I noticed that once you click the "upload" button (in this version I'm using), adding any other files has them upload automatically right away.   It's as though once you use startUpload() ..then the false 'autoSubmit' doesn't seem to apply anymore.    I can probably code around this (and, it could be that this functionality might be good in the end); however, I thought it worth mentioning.   If you designed it this way on purpose, then please disregard my comment, as I'm sure it's just fine as it is.

Thanks in advance!

**Comment by hayageek** [comment]
For me validation is failing in Firefox.
What fields i need to select for "Instrument", "Ensemble"
![capture](https://cloud.githubusercontent.com/assets/2642670/9714828/68223878-558d-11e5-9342-b8166468af38.PNG)

**Comment by Amadeus-** [comment]
That is strange -- it works fine in Chrome.   I'll have to download Firefox and determine why the validation doesn't work.   I followed pretty simple jquery howtos on form validation that I found, so it didn't occur to me that there might be browser incompatibilities.

I'll test it with firefox and reply back here if I have the validation fixed and it's still an issue with the event.

Thanks!

**Comment by Amadeus-** [comment]
OK -- I fixed the form validation at http://maestro.isxgames.com/test/ and it is now working with Internet Explorer, so I hope it will work for you in your browser.    (What's strange is that it shouldn't have worked in Chrome...but did, for some odd reason.)     Anyway, the event issue is still present, so hopefully you'll be able to properly test it and see the problem.

Again, sorry for the inconvenience earlier.

**Comment by hayageek** [comment]
Strange. Same code is working in my website :(

Working:
http://hayageek.com/examples/jquery/jquery-multiple-file-upload/testbed/one.html

Can you take this latest javascript plugin.
http://hayageek.com/examples/jquery/jquery-multiple-file-upload/testbed/jquery.uploadfile.min.js

**Comment by Amadeus-** [comment]
OK, so yea, I guess that's the issue.    Version 3.1.10 (from the link you provided) does work ...however, version 4.0.4 (from github) does not.   Did you test it with the version from github?    

Honestly, I was just doing a clone of your git locally so I could make sure that I always had a copy available on the local server.  It never occurred to me that the version on github would not be the one you'd want us to use.

Anyway, I can use the version you provided!    Let me know when it's fixed on the latest version and I'll do a 'git pull' and go back to using the latest version.   Thanks!

**Comment by hayageek** [comment]
Finally fixed issue.
Get the latest code 
or

http://hayageek.github.io/jQuery-Upload-File/4.0.5/jquery.uploadfile.min.js

**Comment by hayageek** [comment]
Please let me know the issue. I will check GitHub version also
