### ISSUE TITLE
Node/Browserify module

### ISSUE THREAD

**Issue by drschwabe** [hayageek/jquery-upload-file#65]
Although there is a package.json which let's us install via npm, the library itself does not work as a node module ie- ```var fileUpload = require('jquery-upload-file')```

**Comment by folksy** [comment]
Hello,

Thank you for contacting Folksy Support. We aim to respond to
queries within one working day but we will get back to you as
soon as possible.

Our standard Support hours are 9am GMT/BST to 5pm GMT/BST
Monday-Friday.

Please note that we offer limited support at the weekends and on
UK Bank Holidays:

https://www.gov.uk/bank-holidays ( https://www.gov.uk/bank-holidays )

While you are waiting, please take a look at our Knowledge Base
for answers to our most frequently asked questions:

http://folksy.uservoice.com/knowledgebase ( http://folksy.uservoice.com/knowledgebase )

If your enquiry relates to a service-critical issue out of office
hours (e.g. your shop has been restricted and you are unable to
process orders), please email us at urgent@folksy.co.uk (
mailto:urgent@folksy.co.uk )

Thank you,

Folksy Support

-----

Email: support@folksy.com ( mailto:support@folksy.com )

Helpdesk (buyer and seller FAQs): http://folksy.uservoice.com/ ( http://folksy.uservoice.com/ )

Blog (including seller tips): http://blog.folksy.com ( http://blog.folksy.com )

Forums (talk to our community): http://talk.folksy.com ( http://talk.folksy.com )

On September 07, 2015 at 5:06 PM hayageek/jquery-upload-file
wrote:

Although there is a package.json which let's us install via
npm, the library itself does not work as a node module ie- ```var
fileUpload = require('jquery-upload-file')```

---

Reply to this email directly or view it on GitHub:

https://github.com/hayageek/jquery-upload-file/issues/65 ( https://github.com/hayageek/jquery-upload-file/issues/65 )

Powered by UserVoice. ( http://www.uservoice.com/powered-by?utm_campaign=poweredby&utm_medium=email&utm_source=ticket&uv_company=Folksy&uv_contact_url=folksy.uservoice.com&uv_experience=email )

**Comment by hayageek** [comment]
Fixed issue.

**Comment by drschwabe** [comment]
Wow great, thanks!
