### ISSUE TITLE
two file uploaders in one page

### ISSUE THREAD

**Issue by sanaalauddin** [hayageek/jquery-upload-file#68]
I want to have two file uploaders in the same page. One will be single file upload only and the other will be multiple file upload with extra html elements . I had tried to implement this. But only one seems to work. Im using Codeigniter Framework. Your response will be highly appreciated.

**Comment by folksy** [comment]
Hello,

Thank you for contacting Folksy Support. We aim to respond to
queries within one working day but we will get back to you as
soon as possible.

Our standard Support hours are 9am GMT/BST to 5pm GMT/BST
Monday-Friday.

Please note that we offer limited support at the weekends and on
UK Bank Holidays:

https://www.gov.uk/bank-holidays ( https://www.gov.uk/bank-holidays )

While you are waiting, please take a look at our Knowledge Base
for answers to our most frequently asked questions:

http://folksy.uservoice.com/knowledgebase ( http://folksy.uservoice.com/knowledgebase )

If your enquiry relates to a service-critical issue out of office
hours (e.g. your shop has been restricted and you are unable to
process orders), please email us at urgent@folksy.co.uk (
mailto:urgent@folksy.co.uk )

Thank you,

Folksy Support

-----

Email: support@folksy.com ( mailto:support@folksy.com )

Helpdesk (buyer and seller FAQs): http://folksy.uservoice.com/ ( http://folksy.uservoice.com/ )

Blog (including seller tips): http://blog.folksy.com ( http://blog.folksy.com )

Forums (talk to our community): http://talk.folksy.com ( http://talk.folksy.com )

On Sep 21, 2015 at 5:24 AM hayageek/jquery-upload-file wrote:

I want to have two file uploaders in the same page. One will be
single file upload only and the other will be multiple file
upload with extra html elements . I had tried to implement this.
But only one seems to work. Im using Codeigniter Framework. Your
response will be highly appreciated.

---

Reply to this email directly or view it on GitHub:

https://github.com/hayageek/jquery-upload-file/issues/68 ( https://github.com/hayageek/jquery-upload-file/issues/68 )

Powered by UserVoice. ( http://www.uservoice.com/powered-by?utm_campaign=poweredby&utm_medium=email&utm_source=ticket&uv_company=Folksy&uv_contact_url=folksy.uservoice.com&uv_experience=email )

**Comment by hayageek** [comment]
You can have N number of uploaders. My demo page contains many uploaders .
Can u share me the code to fix
