### ISSUE TITLE
Upload is broken when autoSubmit=false and one of the files removed

### ISSUE THREAD

**Issue by Batronix** [hayageek/jquery-upload-file#69]
Configure autoSubmit: false, select few files for upload, than remove last one, try to run uploader.startUpload() and browser redirects to upload url - form is just being submitted in old fashion way.
The problem is in onCancel() handler on line 868:
pd.cancel.click(function () {
mainQ.pop(); /// !!! always removes last file form whereas should remove current form

here is the fix:
mainQ.splice(mainQ.indexOf(form), 1);

**Comment by hayageek** [comment]
Thanks. Fixed the issue.
