### ISSUE TITLE
Selected file auto submits after deleting a file from the list and autoSubmit is set to FALSE.

### ISSUE THREAD

**Issue by UWiX-nl** [hayageek/jquery-upload-file#70]
I've set the option autoSubmit to FALSE and the users needs to click a "Start Upload" button after selecting some files to upload.
This works fine until the user delete's one or two uploads and wants to select another file to upload. When the user have selected a new file it get's automaticly uploaded.

Seems to me the user has to press the "Start Upload" button again when selecting another file to upload. This is more logical and should not set the autoSubmit to TRUE, is it?

**Comment by hayageek** [comment]
I will fix by EOD

**Comment by UWiX-nl** [comment]
That would be great! Thank you!

**Comment by hayageek** [comment]
Fixed issue.
