### ISSUE TITLE
Event that handles dragged but never dropped

### ISSUE THREAD

**Issue by abishekrsrikaanth** [hayageek/jquery-upload-file#72]
Hi,

Is there an event that is invoked if a file is dragged from the file explorer, dragged over the the drag area, but is not dropped on the dragged area and is dropped back on the file explorer. I currently have the drag and drop enabled on the document. When I drag over the document, I can show the appropriate event changes but when I dont drop the files on the document and drop it back on the file explorer, I am having trouble invoking an event. Could you please advice on how to implement this?

**Comment by hayageek** [comment]
javascript supports

dragenter,dragover,drop,dragleave

So you can use dragleave event.
https://github.com/hayageek/jquery-upload-file/blob/master/js/jquery.uploadfile.js
