### ISSUE TITLE
After deleting an upload the same can not be uploaded again (file exists error).

### ISSUE THREAD

**Issue by UWiX-nl** [hayageek/jquery-upload-file#74]
Sorry to keep bothering you with stuff but I think this time it isn't my "programming error" ;-)

I've set the upload settings to a max of 2 files. After selecting to files I click the "Start Upload" and everything works fine. The files get uploaded correctly.
I've also set the showDelete value to TRUE so a nice "Delete" button is shown next to the uploaded files. 
After clicking "Delete" for let say "filename01.png" I click the "Select Files" button again and one more time I select the "filename01.png" file (e.g. I deleted the wrong file from the list).
This time when I've selected that file the error "filename01.png is not allowed. File already exists." error appears. Only after refreshing the page I can select new files, well, I'll have to start all over again.

How are the uploaded filenames stored? I mean in what variable I can access or clear for usage in the "deleteCallback" function?

Thank you. Again! :-)

**Comment by hayageek** [comment]
Did u set allowDuplicates to false. ? Otherwise there should not be any
problem
BTW, do U have the latest plugin

**Comment by UWiX-nl** [comment]
Yes,  I have set allowDuplicate to false but... If I delete the file it shouldn't be a duplicate anymore,  because it is erased isn't it? In that case it is not a duplicate anymore. 

I'm using the latest version of your script so that should be okay ☺

**Comment by hayageek** [comment]
It is a bug, will be fixed by tomorrow

**Comment by UWiX-nl** [comment]
Wow,  that's a fast service.  Thank you very much.

**Comment by hayageek** [comment]
Fixed issue.

http://hayageek.github.io/jQuery-Upload-File/4.0.9/jquery.uploadfile.min.js

**Comment by UWiX-nl** [comment]
Thank you for your quick respons - the problem is solved now. :+1:
