### ISSUE TITLE
Suggestion for next version: PHP max. upload filesize check.

### ISSUE THREAD

**Issue by UWiX-nl** [hayageek/jquery-upload-file#75]
Maybe a suggestion for a next version. When no upload limit is set and a user uploads a large file all seems to upload correctly; the statusbar is shown, the uploadprogress is shown and finally a "Done" message is made, but.... when the file exceeds the PHP uploadsize limit the file isn't actually uploaded.

Is it an idea to check for a post_max_size to set as default upload limit for the jquery-upload-file code when no upload limit is set by me as a programmer?

**Comment by hayageek** [comment]
Plugin handles custom errors.  return the error if file size bigger than upload size.

	$custom_error= array();
	$custom_error['jquery-upload-file-error']="File size is more than the server settings.";
	echo json_encode($custom_error);
	die();

**Comment by UWiX-nl** [comment]
You're right.I'm still learning every day. Thank you (again and again) ;-)

**Comment by UWiX-nl** [comment]
There's another but over here.... I was looking for a sample in your documentation for the custom_errors but not sure how to implement.
I can say the onError Callback works for errors returned by the plugin but in case of the post-max-size from PHP it doesn't return any error. 
The plugin "simulates" a correct upload but nothing is uploaded. That's okay because I will generate the options for the plugin dynamicly so I can check the PHP POST-MAX-SIZE in the php source file.

Also I've found some discussion on your documentation page about the script not receiving server errors - so guess it has to do something with that.

**Comment by hayageek** [comment]
you need to set returnType:"json",  because it is expecting JSON object. 
your onError callback is called.
From the code:
 s.onError.call(this, fileArray, 200, msg, pd);

onError:function(files,code,mesage,pd)
{

}

**Comment by UWiX-nl** [comment]
returnType is indeed set to "json". No halting on error, but... it is probaly a programmer error on my behalf, so closing the issue. Thank you for the heads-up ;-)
