### ISSUE TITLE
error message wordpress

### ISSUE THREAD

**Issue by lilianme** [hayageek/jquery-upload-file#76]
Hello everyone,

I have a big problem and saw a earlear post white the same problem. When i want to pay in my website white ideal, this error occeur SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data. Have anywhone a answer?

Thank you in advance

**Comment by hayageek** [comment]
Becauase you set returnType:"json", but you are returning non-JSON data. check the upload.php response

**Comment by lilianme** [comment]
Thank you for answere but i dont understand i always work with druppal and sinds two days wordpress i cannot find file upload php?? Sorry but where is it? Wat can i Do
![schermafbeelding 2015-10-23 om 23 06 15](https://cloud.githubusercontent.com/assets/15252457/10705157/4498e668-79dc-11e5-9924-0f23c4effd0b.png)
![schermafbeelding 2015-10-23 om 23 05 57](https://cloud.githubusercontent.com/assets/15252457/10705156/4496b730-79dc-11e5-9667-962c767ed070.png)

**Comment by hayageek** [comment]
In the network tab, check the response from upload response
