### ISSUE TITLE
Change upload button text using js

### ISSUE THREAD

**Issue by kkbkrishna** [hayageek/jquery-upload-file#77]
Is there a way i can change the upload button text using javascript. 

I have buttons in my webpage to change language. I change all the label texts using jquery. I would like to do the same for the upload button. Please help

**Comment by hayageek** [comment]
uploadStr:"Upload"

You can use 
 abortStr: "Abort",
            cancelStr: "Cancel",
            deletelStr: "Delete",
            doneStr: "Done",
            multiDragErrorStr: "Multiple File Drag &amp; Drop is not allowed.",
            extErrorStr: "is not allowed. Allowed extensions: ",
            duplicateErrorStr: "is not allowed. File already exists.",
            sizeErrorStr: "is not allowed. Allowed Max size: ",
            uploadErrorStr: "Upload is not allowed",
            maxFileCountErrorStr: " is not allowed. Maximum allowed files are:",
            downloadStr: "Download",

**Comment by kkbkrishna** [comment]
Can this be done on a button click?

**Comment by kkbkrishna** [comment]
Can I change the texts on a button click or a jquery event?

**Comment by hayageek** [comment]
there is a method. update(), you can chnage the values.
