### ISSUE TITLE
Cancel button functionality in custom bar

### ISSUE THREAD

**Issue by sanaalauddin** [hayageek/jquery-upload-file#78]
Hi. I will appreciate if you can help me out. Below is a screenshot of how I want to show the upload bar. How can I get the traditional Cancel functionality into my Cancel button?
Thanks.

![upload](https://cloud.githubusercontent.com/assets/12517730/10861284/b35d0d6c-7f50-11e5-83c8-6309c03987bb.png)

**Comment by hayageek** [comment]
Ho you can customise the progress , check the Featured tab in demo page

**Comment by sanaalauddin** [comment]
Hi. Thanks for the reply. I want to append each upload to a table at the end of the page. But even if I add it as a row (tr) it is going to the div under my upload button. How can I fix that? Thanks.

**Comment by hayageek** [comment]
Can you share your code

**Comment by sanaalauddin** [comment]
Hi Ravi,
I have emailed you the view file. Kindly check. I highly appreciate your effort. Thanks.
