### ISSUE TITLE
Callback when user clicks to choose file(s)

### ISSUE THREAD

**Issue by Amadeus-** [hayageek/jquery-upload-file#79]
I know this may seem like a silly request; however, I could use an event callback when a person actually clicks the "choose files".    The reason for this is because I want to be able to keep an accurate log of everything a user does (in case there are problems), and I would like to make sure that the user has set their name on the form before allowing them to do anything else.    So, in the callback, I would check if the "name" fields are set on the form, and then allow it to continue if so, or provide an error message (and reset the "choose files") if so.

Hopefully this makes sense.  I know it would seem odd to have an "OnClickSelect", when there is already an "OnSelect" callback, but I can't think of any other way to keep a user from choosing a file before they enter other information on the form.

Or, if anyone has suggestions or thoughts that I might be missing, please feel free to suggest!

**Comment by hayageek** [comment]
Not a usefull method for all.
