### ISSUE TITLE
Overlapping uploads

### ISSUE THREAD

**Issue by Freelaxed** [hayageek/jquery-upload-file#82]
Hi, i have a problem with this: when i start an upload while another upload is still running, the submit is fired twice. For the running upload the submit is fired for the second time. At the end i have three submits. Am i missing Some setting or is there something else wrong?

**Comment by hayageek** [comment]
Are u using latest plugin. Can you share your URL?

Email me : ravi@hayageek.com

**Comment by hayageek** [comment]
startUpload() is not designed to call multiple times when the upload in progress.

**Comment by hayageek** [comment]
I will try to provide a fix.

**Comment by hayageek** [comment]
Fixed the issue. You can get from 

http://hayageek.com/examples/jquery/jquery-multiple-file-upload/jquery.uploadfile.js

I will update the plugin in github by tomorrow.

**Comment by Freelaxed** [comment]
Thank you for your reply! 

Can i get it from the provided link right now? Or should i wait for github?

With regards,

John Kolen

**Comment by hayageek** [comment]
You can take this. Same code i will upload by end of tomorrow. I will
update u
