### ISSUE TITLE
Upload of multiple files sometimes redirects page to `url`

### ISSUE THREAD

**Issue by VipSaran** [hayageek/jquery-upload-file#84]
I'm using these options:

```
url: '/api/files',
autoSubmit: false
```

The upload works fine, but sometimes, during the upload, the page is redirected to `url`. This naturally breaks the upload and the previous page needs to be reloaded.

Even though I have used "Preserve Log" in Chrome console, no error is seen. Just after last successfull upload log entry (onSuccess callback), this is logged: `Navigated to http://localhost/api/files`.

**Comment by hayageek** [comment]
I never saw this kind of problem, can you help me to reproduce the issue.
Which browser ? which OS ? what is the filesize. ?

**Comment by VipSaran** [comment]
Chrome latest, 64bit.
Windows 10.
100kB - 10MB files, regardless.
Happened locally (XAMPP) and online.

I'll email you access to server.

**Comment by VipSaran** [comment]
Did you get my mail? I see you didn't try reproducing the problem on the server...
Is there anything I can do to help solve this problem?

**Comment by hayageek** [comment]
issue is solved ?

**Comment by VipSaran** [comment]
That part of project was on hold for a month, but I'm just starting again on it.
I'll check with a colleague if he noticed the issue in the meantime and will get back to you, but I think the problem didn't magically disapear in the meantime :(

**Comment by VipSaran** [comment]
Still fails.
I've resent you the email with access details.

**Comment by VipSaran** [comment]
I have finally found when the error comes and I can reproduce it consistently.

I'm using sequential mode.

1. init the form with uploadFile()
2. upload 3 files
3. (close modal window and reset the form)
4. init the form with uploadFile()
5. upload 3 different files
6. redirect happens after last file is uploaded

Why?  Because when step 5 is started, **mainQ suddenly and unexpectedly increases in size!**.
When uploading 3 files, it starts with length=3 but suddenly becomes length=4 9as in attached example log). When uploading 8 files, it starts with 8, but jumps to length=14.
Those additional forms in the queue cause the extra request (which in my case is unauthorized).

So, please take look at the log:
[localhost-1481218910233.zip](https://github.com/hayageek/jquery-upload-file/files/640175/localhost-1481218910233.zip)

And here is your script with some logging:
[jquery.uploadfile.zip](https://github.com/hayageek/jquery-upload-file/files/640174/jquery.uploadfile.zip)

**Comment by hayageek** [comment]
are you using jQuery UI for modal window ?
How you are resetting the form. ? using  .reset() method ?

If you are using reset() method, can you try with attached file. ?
[jquery.uploadfile.js.zip](https://github.com/hayageek/jquery-upload-file/files/641300/jquery.uploadfile.js.zip)

**Comment by hayageek** [comment]
Can you share your actual code ?

**Comment by VipSaran** [comment]
I've already tried resetting the arrays in the reset() function -- like now, no help.

This is the relevant part of my markup:
```
  <div class="ui modal" id="hsModal">
    <div class="content">
      <div class="ui grid">
        <div class="left floated three wide column">
          <h3>
          Point&nbsp;<span id="hotspot_id"></span>
          </h3>
        </div>
        <div class="right floated twelve wide column" id="hotspot_user"></div>
      </div>
      <div class="ui fluid transparent input">
        <input data-l10n-id="enter_description" id="hotspot_description" type="text" placeholder="Enter description...">
      </div>
      <div class="ui divider"></div>
      <div class="ui row" id="uploadFormContainer">
        <form id="uploadForm" method="POST" enctype="multipart/form-data"><input type="file" name="file" accept="*" style=""></form>
        <div data-l10n-id="upload_all" id="uploadButton" class="ui button blue uploadButton">Upload all</div>
        <div id="eventsMessages" class="ui negative message hidden">
          <i class="close icon"></i>
          <div data-l10n-id="errors" class="header">
            Errors:
          </div>
          <div class="msg"></div>
        </div>
      </div>
      <div class="row">
        <div class="fluid" style="text-align: center;">
          <a data-l10n-id="open_in_management" id="openInManagement" href="#" target="_blank">
            <i class="linkify icon"></i>
            Open in admin page
          </a>
        </div>
      </div>
    </div>
    <div class="actions">
      <div data-l10n-id="btn_delete" class="ui deny red button">
        Delete
      </div>
      <div data-l10n-id="btn_save" class="ui positive left floated button">
        Save
      </div>
      <div data-l10n-id="btn_close" class="ui left floated basic button" tabindex="0">
        Close
      </div>
    </div>
  </div>
```

and this is the relevant part that handles it:
```
function showModal(hotspot_id, atv, ath, callback) {
  console.log('showModal', hotspot_id);

  initUploadForm(hotspot_id);

  $('#hotspot_id').html(hotspot_id);
  if (hotspots[hotspot_id]) {
    $('#hotspot_description').val(hotspots[hotspot_id].description);
    $('#hotspot_user').html(hotspots[hotspot_id].user_name + ',&nbsp;' + hotspots[hotspot_id].customer_name);
  }

  $("#hsModal").modal("setting", {
    closable: false,
    onApprove: function($button) {
      console.log('approve', $button);

      $.ajax({
        type: 'PUT',
        url: '/api/hotspot/' + hotspot_id,
        dataType: 'json',
        data: JSON.stringify({
          'description': $('#hotspot_description').val(),
          'atv': atv,
          'ath': ath
        }),
        cache: false,
        headers: {
          'Authorization': authToken
        },
        beforeSend: function(jqXHR, settings) {
          disableButtons();
        },
        success: function(data, textStatus, jqXHR) {
          if (data.error) {
            console.error('success, data.error=', data.error);
            showGeneralMessages(data.error);

            callback(false);
          } else {
            console.log('success, data=', data);
            var backup_files = hotspots[hotspot_id].files;
            var backup_color = hotspots[hotspot_id].color;
            var backup_user_name = hotspots[hotspot_id].user_name;
            var backup_customer_name = hotspots[hotspot_id].customer_name;

            hotspots[hotspot_id] = data;
            hotspots[hotspot_id].files = backup_files;
            hotspots[hotspot_id].color = backup_color;
            hotspots[hotspot_id].user_name = backup_user_name;
            hotspots[hotspot_id].customer_name = backup_customer_name;

            callback(true);
          }
        },
        error: function(jqXHR, textStatus, errorThrown) {
          if (jqXHR) {
            if (jqXHR.status == 401) {
              relogin();
            }
          }
        },
        complete: function(jqXHR, textStatus) {
          resetUploadForm();
          enableButtons();
        }
      });
      return false;
    },
    onDeny: function($button) { /* handle delete */}
  }).modal("show");

  $('#hsModal .basic').unbind('click.showModal');
  $('#hsModal .basic').bind('click.showModal', function() {
    console.log('close modal');
    resetUploadForm();
    callback(false);
  });

  $("#uploadFormContainer").off('resize');
  $("#uploadFormContainer").resize(function() {
    _.throttle(function() {
      console.log('resize modal');
      $("#hsModal").modal("refresh");
    }, 200, {
      'leading': false
    });
  });
}

function resetUploadForm() {
  $("#hsModal").modal("hide");
  $("#uploadButton").hide();
  if (uploadFormObj) {
    uploadFormObj.reset();
  } else {
    $(".ajax-file-upload-container").remove();
  }
  closeEventsMessages();
}
```

Hope it helps.

**Comment by hayageek** [comment]
from the code, I could see you initializing the plugin  every time when the modal is shown.

can you use this plugin: https://github.com/hayageek/jquery-upload-file/files/641300/jquery.uploadfile.js.zip

make sure     uploadFormObj.reset() called once the modal is closed

**Comment by VipSaran** [comment]
Like replied to [comment](https://github.com/hayageek/jquery-upload-file/issues/84#issuecomment-265936688) where you previously linekd that same file:
> I've already tried resetting the arrays in the reset() function -- **like now, no help**.

So, the changes you have made -- reinitializing the arrays in the reset() function -- did not help, unfortunately.

As you can see, uploadFormObj.reset() is called from resetUploadForm() which is called then the modal is closed...

**Comment by hayageek** [comment]
Can you share me your URL ?
my mail id : ravi@hayageek.com

**Comment by VipSaran** [comment]
I'll mail you the access details in 2 days. I'm on a trip currently.

**Comment by VipSaran** [comment]
Just sent you the email with access details...
