### ISSUE TITLE
Duplicate image if "Done" button appear at same time

### ISSUE THREAD

**Issue by howardhee** [hayageek/jquery-upload-file#92]
I have selected 4 different image to upload to server, but when done button displayed at the same time,image will duplicated, quantity for images are correct (total 4 images), but 2 of it is duplicate. Means only 3 different photos are uploaded, 1 photo is duplicate. Any handling for upload photo one by one to prevent this?

![untitled1](https://cloud.githubusercontent.com/assets/4166688/12389533/5bc1bdac-be14-11e5-8024-5001dce3c396.png)

**Comment by hayageek** [comment]
I think two files are having same file name, you need to rename at Server.
One is overwriting other

**Comment by howardhee** [comment]
Ya, I checked in database, file name are same. But if you see the upload list from screenshot. The file name and size is different. Any solution for upload file one by one automatically?

**Comment by hayageek** [comment]
If you rename the file, and returns the new Filename in the response , it
should work find

**Comment by howardhee** [comment]
I am using date("YmdHis") as file name, so if completed same time, file name will duplicated. I follow your tutorial from link http://hayageek.com/jquery-multiple-file-upload/ . I tried use  code below to loop the selected file, but it always get single file condition instead of multiple files condition even i selected multiple. 

if(!is_array($_FILES["myfile"]['name'])) //single file
    	{
       	 	$fileName = $_FILES["myfile"]["name"];
       	 	move_uploaded_file($_FILES["myfile"]["tmp_name"],$output_dir. $_FILES["myfile"]["name"]);
	       	 	 $ret[$fileName]= $output_dir.$fileName;
    	}
    	else
    	{
    	    	$fileCount = count($_FILES["myfile"]['name']);
    		  for($i=0; $i < $fileCount; $i++)
    		  {
    		  	$fileName = $_FILES["myfile"]["name"][$i];
	       	 	 $ret[$fileName]= $output_dir.$fileName;
    		    move_uploaded_file($_FILES["myfile"]["tmp_name"][$i],$output_dir.$fileName );
    		  }
    	
    	}

**Comment by hayageek** [comment]
issue is solved ?
