### ISSUE TITLE
multiple:false does not work

### ISSUE THREAD

**Issue by Cyrille37** [hayageek/jquery-upload-file#93]
Hi,
Thanks for that nice plugin.

With the above setting *multiple:false*  I can select several files, they're uploaded and previewed.

```
		$('#fieldImage').uploadFile({
			url: '/upload',
			fileName: 'image',
			returnType: 'json',
			acceptFiles: 'image/*',
			multiple: false,
			allowDuplicates: false,
			showPreview: true,
			previewHeight: '120px',
			previewWidth: '120px',
			uploadStr: 'Sélectionnez un fichier'
		});
```
By the way, the setting *allowDuplicates:false* works fine.

Any idea ?
Cheers.

**Comment by hayageek** [comment]
multiple:false does not allow each selection. If you want to limit the files, use maxFileCount:1

**Comment by Cyrille37** [comment]
Ok, thanks. It works.
Cheers
