### ISSUE TITLE
Question on How to Use Upload File

### ISSUE THREAD

**Issue by samuvk** [hayageek/jquery-upload-file#98]
I'm trying to use Jquery-upload-file with the following HTML
`<head>
<link href="http://hayageek.github.io/jQuery-Upload-File/4.0.10/uploadfile.css" rel="stylesheet">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="http://hayageek.github.io/jQuery-Upload-File/4.0.10/jquery.uploadfile.min.js"></script>
</head>
<body>

<div id="fileuploader">Upload</div>

<script>
$(document).ready(function()
{
	$("#fileuploader").uploadFile({
	url:"http://localhost/images/",
	fileName:"myfile"
	});
});
</script>`

and I'm getting the following error message:  (same if I use: url:"/var/www/html/images/",)
1.jpg (32.34 KB)
ERROR: NS_ERROR_DOM_BAD_URI: Access to restricted URI denied

Thank you so much

**Comment by hayageek** [comment]
You should not give images URL. You should give the path of uploader script
path

**Comment by samuvk** [comment]
The uploadfile.jquery.json?  the jquery.uploadfile.js? or none of those?
Thanks

**Comment by hayageek** [comment]
Can you share me your code

**Comment by samuvk** [comment]
Please find files attached. The one I created is the uploadimages.html
Thank you so much
[Upload-Files.zip](https://github.com/hayageek/jquery-upload-file/files/204537/Upload-Files.zip)

**Comment by hayageek** [comment]
files are not saved to the folder you specify in the url path.

url should be a upload handler.

example:
url:"http://localhost/SweatMeal/upload.php"

where upload.php source
https://github.com/hayageek/jquery-upload-file/blob/master/php/upload.php
