### ISSUE TITLE
Kohana ERROR: Forbidden

### ISSUE THREAD

**Issue by aksebkit** [hayageek/jquery-upload-file#99]
Hi, I'm trying to use script in Kohana Framework, but it only give me error Forbidden. 
Any help?

**Comment by hayageek** [comment]
can you share me screenshot or code or URL ?

**Comment by hayageek** [comment]
I think uploadURL is not found.

**Comment by aksebkit** [comment]
Allright, I was not sending it to controller.

Now POST works, but I've never saved anything using kohana and POST. Any help?
